// NOTICE:JSON記述が正しくないとevalでエラーとなり、CONFIGを読み込めない
var CONFIG = {
  "DEBUG_MODE": false,
  "APP_NAME": "app_mdTableToJson.jse",
  "ENCODE" : "utf-8"
}

CONFIG.IS_CHECKED_FORM = true;
CONFIG.FORMAT_FNAME = 'FORMAT';
CONFIG.FORMAT_SHEETID = 'TD';
CONFIG.TABLE_HEAD = 'no';
CONFIG.TABLE_HEAD_POS = 1;
CONFIG.TABLE_COLSIZE = 7;

