// NOTICE:JSON記述が正しくないとevalでエラーとなり、CONFIGを読み込めない
var CONFIG = {
  "DEBUG_MODE": false,
  "APP_NAME": "./app_commentInOut.jse"
}

CONFIG.CONS_QUOTE_STRING = '> ';
CONFIG.CONS_COMMENT_SLASH = '// ';
CONFIG.CONS_TARGET_SLASH = ['cs', 'cpp', 'java', 'js', 'jse'];
CONFIG.CONS_COMMENT_SHARP = '# ';
CONFIG.CONS_TARGET_SHARP = ['ini', 'ps1', 'psd1', 'ts', 'py', 'pl', 'rb', 'php', 'coffee'];
CONFIG.CONS_COMMENT_SEMICOLON = '; ';
CONFIG.CONS_TARGET_SEMICOLON = ['bat', 'cmd', 'ahk'];
CONFIG.CONS_COMMENT_QUATATION = "' ";
CONFIG.CONS_TARGET_QUATATION = ['vb', 'vbs'];
CONFIG.CONS_COMMENT_HYPHEN = "-- ";
CONFIG.CONS_TARGET_HYPHEN = ['sql', 'plsql'];
CONFIG.CONS_COMMENT_PERCENT = "% ";
CONFIG.CONS_TARGET_PERCENT = ['tex'];

CONFIG.CONS_COMMENT_SET = [
  CONFIG.CONS_COMMENT_SLASH,
  CONFIG.CONS_COMMENT_SHARP,
  CONFIG.CONS_COMMENT_SEMICOLON,
  CONFIG.CONS_COMMENT_QUATATION,
  CONFIG.CONS_COMMENT_HYPHEN,
  CONFIG.CONS_COMMENT_PERCENT
];

CONFIG.CONS_TARGET_SET = [
  CONFIG.CONS_TARGET_SLASH,
  CONFIG.CONS_TARGET_SHARP,
  CONFIG.CONS_TARGET_SEMICOLON,
  CONFIG.CONS_TARGET_QUATATION,
  CONFIG.CONS_TARGET_HYPHEN,
  CONFIG.CONS_TARGET_PERCENT
];
