/*
 *  Sugar Custom 2019.11.12
 *
 *  Freely distributable and licensed under the MIT-style license.
 *  Copyright (c)  Andrew Plummer
 *  https://sugarjs.com/
 *
 * ---------------------------- */
(function(){'use strict';function Nc(a,b){return new ca(a,b)}function B(a,b){for(var c in a)if(J(a,c)&&!1===b.call(a,a[c],c,a))break}function Oc(a){function b(e,f,g){L(d,e,function(h,k,l){h=bc(h,k,l);ze(d,h.methods,f,g,h.w);return d})}var c="Object"===a,d=Pc(a,!0);b("defineStatic",1);b("defineInstance",2);b("defineInstanceAndStatic",3);b("defineStaticWithArguments",1,!0);b("defineInstanceWithArguments",2,!0);L(d,"defineStaticPolyfill",function(e,f,g){e=bc(e,f,g);Ab(Ta[a],e.methods,!0,e.w);return d});L(d,"defineInstancePolyfill",
function(e,f,g){e=bc(e,f,g);Ab(Ta[a].prototype,e.methods,!0,e.w);B(e.methods,function(h,k){Bb(d,k,h)});return d});L(d,"alias",function(e,f){var g=d,h="string"===typeof f?d[f]:f;g[e]=h;h.instance&&Bb(g,e,h.instance,!0);return d});L(d,"extend",function(e){function f(q,t){var w=e[q];if(w)for(var v=0,u;u=w[v];v++)if(u===t)return!0;return!1}function g(q,t){return e[q]&&!f(q,t)}function h(q,t,w){var v;if(v=!(c&&w===l&&(!Qc||"get"===q||"set"===q))){a:if(t=t.flags,w[q]&&t){for(w=0;w<t.length;w++)if(!1===
e[t[w]]){w=!0;break a}w=void 0}else w=!1;v=!w}return v&&!f("except",q)}var k=Ta[a],l=k.prototype,m={},n={};e=e||{};var p=e.methods;if(!f("except",k)&&!g("namespaces",k))return c&&"boolean"===typeof e.objectPrototype&&(Qc=e.objectPrototype),B(p||d,function(q,t){p&&(t=q,q=d[t]);J(q,"instance")&&h(t,q,l)&&(n[t]=q.instance);J(q,"static")&&h(t,q,k)&&(m[t]=q)}),Ab(k,m),Ab(l,n),p||L(d,"active",!0),d});Cb[a]=d;Rc["[object "+a+"]"]=d;Db(a);Ae(d);return C[a]=d}function Be(){return"Sugar"}function ze(a,b,c,
d,e){B(b,function(f,g){var h=f;d&&(h=Sc(f));e&&(h.flags=e);if(c&2&&!f.instance){var k=d?Sc(f,!0):Ce(f);L(h,"instance",k)}c&1&&L(h,"static",!0);k=h;a[g]=k;k.instance&&Bb(a,g,k.instance,!0);a.active&&a.extend(g)})}function bc(a,b,c){if("string"===typeof a){var d={};d[a]=b;a=c}else d=a,a=b;return{w:a,methods:d}}function Sc(a,b){var c=a.length-1-(b?1:0);return function(){var d=[],e=[];b&&d.push(this);var f=Math.max(arguments.length,c);for(var g=0;g<f;g++)g<c?d.push(arguments[g]):e.push(arguments[g]);
d.push(e);return a.apply(this,d)}}function Ce(a){switch(a.length){case 0:case 1:return function(){return a(this)};case 2:return function(b){return a(this,b)};case 3:return function(b,c){return a(this,b,c)};case 4:return function(b,c,d){return a(this,b,c,d)};case 5:return function(b,c,d,e){return a(this,b,c,d,e)}}}function Ab(a,b,c,d){B(b,function(e,f){c&&!d&&a[f]||L(a,f,e)})}function Pc(a){function b(c,d){if(!(this instanceof b))return new b(c,d);this.constructor!==b&&(c=this.constructor.apply(c,
arguments));this.raw=c}L(b,"toString",function(){return"Sugar"+a});L(b.prototype,"valueOf",function(){return this.raw});return b}function Bb(a,b,c){c=De(c);var d;var e=Tc.prototype;var f=(d=e[b])&&d!==Object.prototype[b];d&&d.N||(e[b]=f?Ee(b):c);a.prototype[b]=c;a===C.Object&&Fe(b,c)}function Ae(a){B(C.Object&&C.Object.prototype,function(b,c){if("function"===typeof b){var d=a.prototype;J(d,c)||(d[c]=b)}})}function Fe(a,b){B(Cb,function(c){c=c.prototype;J(c,a)||(c[a]=b)})}function De(a){return function(){return new Tc(a.apply(this.raw,
arguments))}}function Ee(a){function b(){var c=this.raw,d;null!=c&&(d=Rc[ia(c)]);d||(d=C.Object);return(new d(c))[a].apply(this,arguments)}b.N=!0;return b}function Db(a,b){var c=Cb[a],d=Ta[a].prototype;!b&&Uc&&(b=Uc(d));B(b,function(e){if("constructor"!==e&&"valueOf"!==e&&"__proto__"!==e){try{var f=d[e];if("function"!==typeof f)return}catch(g){return}Bb(c,e,f)}})}function Ge(a,b,c){a[b]=c.value}function L(a,b,c,d){Eb(a,b,{value:c,enumerable:!!d,configurable:!0,writable:!0})}function ia(a){return cc.call(a)}
function J(a,b){return!!a&&He.call(a,b)}function A(a,b){if(J(a,b))return a[b]}function Fb(a,b,c){c||(c=ia(a));return c==="[object "+b+"]"}function Na(a){return function(b,c,d){b[a](c,d)}}function Ua(a,b,c,d){S(a,Vc(b,c),d)}function Ie(a,b,c,d){dc(a,Vc(b,c),d)}function Vc(a,b){var c={};H(a)&&(a=ra(a));D(a,function(d,e){b(c,d,e)});return c}function sa(a){function b(c){var d=arguments;return a(c,d[1],d[2],d.length-1)}b.instance=function(c){var d=arguments;return a(this,c,d[1],d.length)};return b}function Wc(a,
b,c){L(a,b,c)}function ec(a,b){function c(e){return d[e]}var d=na({},b);L(a,"getOption",c);Wc(a,"setOption",function(e,f){if(1===arguments.length)var g=e;else g={},g[e]=f;B(g,function(h,k){null===h&&(h=b[k]);d[k]=h})});return c}function Xc(a,b){var c=a.prototype;B(b,function(d,e){c[e]=d})}function Yc(a){if(!a)throw new TypeError("Argument required");}function Ba(a){if(!X(a))throw new TypeError("Function is not callable");}function Va(a){a=+a||0;if(0>a||!Q(a)||!isFinite(a))throw new RangeError("Invalid number");
return da(a)}function y(a){return void 0!==a}function E(a){return void 0===a}function kb(a){var b="_sugar_"+a;return function(c,d){return 1<arguments.length?(L(c,b,d),c):c[b]}}function Zc(a,b){a.prototype.constructor=function(){return b.apply(this,arguments)}}function ta(a){if(!Ca(a)){var b=ia(a);if(Da(a,b))return Je(a);if(ha(a,b))return Ke(a);if(X(a,b))return Le(a);if(Gb(a,b))return Me(a)}return Ne(a)}function Me(a){var b={};return function(c,d,e){var f=!0;if(!T(c))return!1;B(a,function(g,h){b[h]=
A(b,h)||ta(g);!1===b[h].call(e,c[h],d,e)&&(f=!1);return f});return f}}function Ne(a){return function(b){return Oa(b,a)}}function Je(a){a=RegExp(a);return function(b){return a.test(b)}}function Ke(a){var b=a.getTime();return function(c){return!(!c||!c.getTime)&&c.getTime()===b}}function Le(a){return function(b,c,d){return b===a||a.call(d,b,c,d)}}function Hb(a,b,c){return Wa(a,b,c,!1)}function Wa(a,b,c,d,e,f,g){var h=a||void 0;if(null!=b){if(T(b))a=[b];else{b=String(b);if(-1!==b.indexOf(".."))return Oe(a,
b,c,g);a=b.split("[")}var k=y(g);for(var l=0,m=a.length;l<m;l++){var n=a[l];H(n)&&(n=n.split("."));for(var p=0,q=n.length;p<q;p++){b=n[p];var t=l===m-1&&p===q-1;var w=b.indexOf("]");var v=-1!==w;var u=k&&0===w;w=1<m&&p===q-1;u?b=h.length:v&&(b=b.slice(0,-1));v&&0>b&&(b=+b+h.length);if(l||b||1===m)if(v=c?b in h:J(h,b),!e||t&&!f||v){if(d){if(t||!v)return v}else if(k&&t){if(Ca(h))throw new TypeError("Property cannot be written");h[b]=g}h=v?h[b]:void 0}else h=h[b]=w||f&&t?[]:{}}}return h}}function Oe(a,
b,c,d){var e,f;if(e=b.match(Pe)){b=y(d);a=(f=e[1])?Wa(a,f,c,!1,b?!0:!1,!0):a;if(!P(a))throw new TypeError("Array required");var g=e[4];f=e[2]?+e[2]:0;e=e[3]?+e[3]:a.length;e=-1===e?a.length:e+1;if(b)for(b=f;b<e;b++)Wa(a,b+g,c,!1,!0,!1,d);else if(a=a.slice(f,e),g)return"."===g.charAt(0)&&(g=g.slice(1)),a.map(function(h){return Wa(h,g)});return a}}function fc(a,b){if(J(a,b))return b}function T(a,b){return!!a&&"object"===(b||typeof a)}function Ca(a,b){b=b||typeof a;return null==a||"string"===b||"number"===
b||"boolean"===b}function Gb(a,b){var c;if(c=T(a)&&Fb(a,"Object",b))c="constructor"in a,c=!c&&!("toString"in a)||c&&!J(a,"constructor")&&J(a.constructor.prototype,"isPrototypeOf");if(c)a:{c=Object.prototype;for(var d in a){var e=a[d];if(!J(a,d)&&e!==c[d]){c=!1;break a}}c=!0}return c}function Ib(a,b){for(var c=0;c<a;c++)b(c)}function na(a,b){B(b,function(c,d){a[d]=c});return a}function lb(a){Ca(a)&&(a=Object(a));if(Qe&&H(a))for(var b=a,c=0,d;d=b.charAt(c);)b[c++]=d;return a}function Oa(a,b,c){if(a===
b)return 0!==a||1/a===1/b;var d=ia(a);var e=ia(b);return d!==e?!1:Jb(a,d)&&Jb(b,e)?Re(a,b,d,c):Kb(a,d)&&Kb(b,e)?a.size===b.size&&Oa($c(a),$c(b),c):Lb(a,d)&&Lb(b,e)?a.size===b.size&&Oa(ad(a),ad(b),c):Mb(a,d)&&Mb(b,e)?a.toString()===b.toString():!1}function Re(a,b,c,d){if(typeof a!==typeof b)return!1;if(T(a.valueOf())){if(a.length!==b.length)return!1;var e=0;var f=!0;bd(a,!1,d,function(g,h,k,l){k||g in b&&Oa(h,b[g],l)||(f=!1);e++;return f});if(!f||e!==Object.keys(b).length)return!1}return a.valueOf().toString()===
b.valueOf().toString()}function Xa(a,b,c){var d=typeof a,e;if(Ca(a,d)&&(null==a||a===a))return d+a;var f=ia(a);if(Jb(a,f))T(a)?e=Se(a,b,c)+a.toString():-Infinity===1/a?e="-0":a.valueOf&&(e=a.valueOf());else return c=gc(b,a),-1===c&&(c=b.length,b.push(a)),c;return d+f+e}function Se(a,b,c){var d="";bd(a,!0,c,function(e,f,g,h){d+=g?"CYC":e+Xa(f,b,h)});return d}function bd(a,b,c,d){function e(g,h){var k=!1;if(1<c.length)for(var l=c.length;l--;)c[l]===g&&(k=!0);c.push(g);d(h,g,k,c);c.pop()}function f(){for(var g=
Object.keys(a).sort(),h,k=0;k<g.length;k++)h=g[k],e(a[h],g[k])}c||(c=[]);b?f():B(a,e)}function cd(a,b,c,d){var e=[],f;for(f in a)f>>>0==f&&4294967295!=f&&(c||(d?f<=b:f>=b))&&e.push(+f);e.sort(function(g,h){var k=g>b;return k!==h>b?k?-1:1:g-h});return e}function dd(a,b,c,d){var e=a.length;if(!P(b))return ed(a,b,e,c,d);var f=Array(b.length);D(b,function(g,h){f[h]=ed(a,g,e,c,d)});return f}function hc(a,b,c){a&&c&&(a%=b);0>a&&(a=b+a);return a}function ed(a,b,c,d,e){b=hc(b,c,d);return e?a.charAt(b):a[b]}
function Ea(a,b,c,d){return b?b.apply?b.apply(c,d||[]):P(b)?b.map(function(e){return Ea(a,e,c,d)}):X(a[b])?a[b].call(a):Hb(a,b):a}function ra(a){return a.split(" ")}function D(a,b){for(var c=0,d=a.length;c<d;c++){if(!(c in a)){d=a;for(var e=b,f=cd(d,c,void 0),g=0,h=f.length;g<h;g++)c=f[g],e.call(d,d[c],c,d);return d}b(a[c],c)}}function ic(a,b){for(var c=[],d=0,e=a.length;d<e;d++){var f=a[d];d in a&&b(f,d)&&c.push(f)}return c}function Fa(a,b){for(var c=[],d=0,e=a.length;d<e;d++)d in a&&c.push(b(a[d],
d));return c}function gc(a,b){for(var c=0,d=a.length;c<d;c++)if(c in a&&a[c]===b)return c;return-1}function mb(a,b,c){var d=Nb(10,oa(b||0));c=c||nb;0>b&&(d=1/d);return c(a*d)/d}function ea(a,b,c,d,e){d=oa(a).toString(d||10);d=jc(e||"0",b-d.replace(/\.\d+/,"").length)+d;if(c||0>a)d=(0>a?"-":"+")+d;return d}function fd(a){if(11<=a&&13>=a)return"th";switch(a%10){case 1:return"st";case 2:return"nd";case 3:return"rd";default:return"th"}}function kc(a,b){var c;var d=a.replace(gd,function(e){e=A(Pa,e);"."===
e&&(c=!0);return e});return c?parseFloat(d):parseInt(d,b||10)}function jc(a,b){var c="";for(a=a.toString();0<b;)if(b&1&&(c+=a),b>>=1)a+=a;return c}function Ya(a){return a.charAt(0).toUpperCase()+a.slice(1)}function hd(a,b,c){function d(m,n){var p=n[2],q=n[3],t=n[5];if(n[4]&&b){var w=t;var v=b}else if(p)w=p,v=a;else var u=q&&b?q:n[1]||n[0];if(v){g(c,p,t);var r=function(x,z){return v(x,w,z)}}m.push(r||f(u))}function e(m,n,p,q){if(q>p){var t=n.slice(p,q);h(t,"{");h(t,"}");m.push(function(){return t})}}
function f(m){return function(){return m}}function g(m,n,p){if(m&&!m(n,p))throw new TypeError("Invalid token "+(n||p)+" in format string");}function h(m,n){if(-1!==m.indexOf(n))throw new TypeError("Unmatched "+n+" in format string");}var k=Te,l=Ue(function(m){var n=[],p=0,q;for(k.lastIndex=0;q=k.exec(m);)e(n,m,p,q.index),d(n,q),p=k.lastIndex;e(n,m,p,m.length);return n});return function(m,n,p){m=l(m);for(var q="",t=0;t<m.length;t++)q+=m[t](n,p);return q}}function id(a){return N.human&&N.human.L(a)||
a}function Za(a,b){function c(e,f){if(e||-1<b.indexOf(f))d+=f}var d="";b=b||"";c(a.global,"g");c(a.ignoreCase,"i");c(a.multiline,"m");c(a.sticky,"y");return d}function $a(a){H(a)||(a=String(a));return a.replace(/([\\\/'*+?|()\[\]{}.^$-])/g,"\\$1")}function Y(a,b){return a["get"+(Z(a)?"UTC":"")+b]()}function ab(a,b,c,d){if(!d||c!==Y(a,b,c))a["set"+(Z(a)?"UTC":"")+b](c)}function Ue(a){var b={},c=0;return function(d){if(J(b,d))return b[d];c===Ve&&(b={},c=0);c++;return b[d]=a(d)}}function $c(a){var b=
Array(a.size),c=0;a.forEach(function(d){b[c++]=d});return b}function ad(a){var b=Array(a.size),c=0;a.forEach(function(d,e){b[c++]=[e,d]});return b}function We(){function a(c,d){for(var e=0;e<b.length;e++)d.push(c+b[e])}var b="FullYear Month Date Hours Minutes Seconds Milliseconds".split(" ");B({Function:"apply,call",RegExp:"compile,exec,test",Number:"toExponential,toFixed,toLocaleString,toPrecision",Object:"hasOwnProperty,isPrototypeOf,propertyIsEnumerable,toLocaleString",Array:"concat,join,pop,push,reverse,shift,slice,sort,splice,toLocaleString,unshift",
Date:"getTime,getTimezoneOffset,setTime,toDateString,toGMTString,toLocaleDateString,toLocaleString,toLocaleTimeString,toTimeString,toUTCString",String:"anchor,big,blink,bold,charAt,charCodeAt,concat,fixed,fontcolor,fontsize,indexOf,italics,lastIndexOf,link,localeCompare,match,replace,search,slice,small,split,strike,sub,substr,substring,sup,toLocaleLowerCase,toLocaleUpperCase,toLowerCase,toUpperCase"},function(c,d){var e=c.split(",");"Date"===d&&(a("get",e),a("set",e),a("getUTC",e),a("setUTC",e));
e.push("toString");Db(d,e)})}function jd(a,b,c,d){var e=a.length;var f=d?-1:1;var g=d?e-1:0;(c=da(c))||0===c||(c=g);0>c&&(c=e+c);if(!d&&0>c||d&&c>=e)c=g;for(g=c;d&&0<=g||!d&&g<e;){if(!(g in a))return Xe(a,b,c,d);if(g>>>0==g&&4294967295!=g&&a[g]===b)return g;g+=f}return-1}function Xe(a,b,c,d){c=cd(a,c,!1,d);var e;for(c.sort(function(f,g){return d?g-f:f-g});void 0!==(e=c.shift());)if(a[e]===b)return+e;return-1}function kd(a,b,c,d){var e=a.length,f=0,g=y(c);Ba(b);if(0!=e||g)g||(c=a[d?e-1:f],f++);else throw new TypeError("Reduce called on empty array with no initial value");
for(;f<e;)g=d?e-f-1:f,g in a&&(c=b(c,a[g],g,a)),f++;return c}function Qa(){return Ye("newDateInternal")()}function Ga(a){var b=new Date(a.getTime());Z(b,!!Z(a));return b}function ld(a){if(isNaN(a.getTime()))throw new TypeError("Date is not valid");}function R(a){return Y(a,"Day")}function pa(a){return Y(a,"Date")}function ja(a){return Y(a,"Month")}function ua(a){return Y(a,"FullYear")}function va(a,b){ab(a,"Date",b)}function md(a){return 32-Y(new Date(ua(a),ja(a),32),"Date")}function Ha(a,b,c){if(Q(b)){var d=
R(a);if(c){c=0<c?1:-1;var e=b%7-d;e&&e/oa(e)!==c&&(b+=7*c)}va(a,pa(a)+b-d);return a.getTime()}}function lc(a,b){var c=Z(a)?0:a.getTimezoneOffset();var d=!0===b?":":"";if(!c&&b)return"Z";var e=ea(da(-c/60),2,!0);c=ea(oa(c%60),2);return e+d+c}function nd(a,b){var c=a[0],d=a[1];if(b&&H(c)){var e={};if(c=c.match(/^(-?\d*[\d.]\d*)?\s?(\w+?)s?$/i)){if(E(f)){var f=+c[1];isNaN(f)&&(f=1)}e[c[2].toLowerCase()]=f}c=e}else Q(c)&&Q(d)?(c=Ze(a),d=null):T(c)&&(c=na({},c));return[c,d]}function Ze(a){var b={},c=0;
od(7,function(d){var e=a[c++];y(e)&&(b[d.name]=e)});return b}function mc(a,b,c){c=c||0;for(E(b)&&(b=7);b>=c&&!1!==a(wa[b],b);b--);}function od(a,b){for(;0<=a&&!1!==b(wa[a],a);)a=ob(a)}function ob(a){return 6===a?4:5===a?3:a-1}function Ob(a,b,c,d){mc(function(e,f){var g=e.name;var h=A(a,nc(a,g));y(h)&&b(g,h,e,f);g=void 0;!1!==g&&4===f&&(g=A(a,nc(a,"weekday")),y(g)&&b("weekday",g,e,f),g=void 0);return g},c,d)}function $e(a,b){Ob(a,b,7,4)}function Ra(a,b,c,d){var e={};e[b]=c;return Ia(a,e,d,1)}function pd(a,
b,c){b=nd(b,!0);return Ia(a,b[0],b[1],c)}function pb(a,b){Ha(a,7*bb((R(a)-b)/7)+b);return a}function qd(a,b){var c=b-1;Ha(a,7*xa((R(a)-c)/7)+c);return a}function qb(a,b,c){5===b&&pb(a,M.get(c).s());return ka(a,ob(b))}function Pb(a,b,c,d){5===b&&qd(a,M.get(c).s());return ka(a,ob(b),d,!0)}function ka(a,b,c,d){od(b,function(e,f){var g=d?e.end:e.start;X(g)&&(g=g(a));ab(a,e.method,g);return!y(c)||f>c});return a}function nc(a,b){return fc(a,b)||fc(a,b+"s")||"day"===b&&fc(a,"date")}function af(a){var b=
{},c;b[a]=1;Ob(b,function(d,e,f,g){c=g;return!1});return c}function Qb(a,b,c){var d=b>a;if(!d){var e=b;b=a;a=e}e=b-a;1<c.f&&(e=da(e/c.f));if(c.m)for(a=Ga(a),e&&Ra(a,c.name,e);a<b;){Ra(a,c.name,1);if(a>b)break;e+=1}return d?-e:e}function rd(a,b){if(Q(b)){var c=Ga(a),d=R(a);ka(c,6);va(c,4);pb(c,1);va(c,pa(c)+7*(b-1));var e=ua(c);ab(a,"FullYear",e);e=ja(c);ab(a,"Month",e);va(a,pa(c));Ha(a,d||7)}return a.getTime()}function cb(a,b,c,d){var e,f=0;E(c)&&(c=1);E(d)&&(d=4);var g=e=qd(Ga(a),c),h=c,k=d;ka(g,
6);va(g,k);pb(g,h);b&&a<e&&(b=e=pb(Ga(a),c),ka(b,6),va(b,d),pb(b,c));for(;e<=a;)va(e,pa(e)+7),f++;return f}function sd(a,b,c){var d=ua(a);var e=ja(a);if(0===e||11===e){if(!c){c=M.get(b);var f=c.s(b);var g=c.G(b)}a=cb(a,!1,f,g);0===e&&0===a?--d:11===e&&1===a&&(d+=1)}return d}function td(a,b,c,d){var e;ld(a);X(c)?d=c:e=c;c=bf(a,b);if(d&&(d=d.apply(a,c.concat(M.get(e)))))return ud(a,d,e);0===c[1]&&(c[1]=1,c[0]=1);a=b?"duration":0<c[2]?"future":"past";return M.get(e).U(c,a)}function vd(a,b){var c=0,d=
0;mc(function(e,f){d=oa(b(e));if(1<=d)return c=f,!1});return[d,c,a]}function cf(a){return vd(a,function(b){return da(mb(a/b.f,1))})}function bf(a,b){b||(b=Qa(),a>b&&(b=new Date(b.getTime()-10)));return vd(a-b,function(c){return oa(Qb(a,b,c))})}function ud(a,b,c){ld(a);b=wd[b]||b||"{long}";return Rb(b,a,c)}function oc(a,b){var c=Y(a,"Hours");return M.get(b).ampm[da(c/12)]||""}function xd(a,b,c){var d;if(!isNaN(a.getTime())){if(H(b))switch(b=b.trim().toLowerCase(),!0){case "future"===b:return a.getTime()>
Qa().getTime();case "past"===b:return a.getTime()<Qa().getTime();case "today"===b:return pc(a);case "tomorrow"===b:return pc(a,1);case "yesterday"===b:return pc(a,-1);case "weekday"===b:return 0<R(a)&&6>R(a);case "weekend"===b:return 0===R(a)||6===R(a);case y(d=Sa.weekdayMap[b]):return R(a)===d;case y(d=Sa.monthMap[b]):return ja(a)===d}return yd(a,b,c)}}function yd(a,b,c,d,e){var f=0,g=0;Z(a)&&(e=e||{},e.fromUTC=!0,e.setUTC=!0);b=rb(null,b,e,!0);if(0<c){f=g=c;var h=!0}if(isNaN(b.date.getTime()))return!1;
if(b.set&&b.set.specificity){if(y(b.set.edge)||y(b.set.shift)){var k=!0;qb(b.date,b.set.specificity,d)}if(k||6===b.set.specificity)var l=Pb(Ga(b.date),b.set.specificity,d).getTime();else l=wa[b.set.specificity],l=Ra(Ga(b.date),l.name,1).getTime()-1;!h&&y(b.set.sign)&&b.set.specificity&&(f=50,g=-50)}c=a.getTime();h=b.date.getTime();l=l||h;if(a=b.set&&b.set.specificity?0:6E4*(b.date.getTimezoneOffset()-a.getTimezoneOffset()))h-=a,l-=a;return c>=h-f&&c<=l+g}function pc(a,b){var c=Qa();b&&va(c,pa(c)+
b);return ua(a)===ua(c)&&ja(a)===ja(c)&&pa(a)===pa(c)}function ya(a,b,c){return rb(null,a,b,c).date}function rb(a,b,c,d){function e(x,z){var F=A(v,"params")||{};D(z.to,function(O,Ja){var K=x[Ja+1];if(K){if("yy"===O||"y"===O){O="year";var U=A(v,"prefer");K=+K;K+=50>K?2E3:1900;if(U){var fa=K-ua(u);fa/oa(fa)!==U&&(K+=100*U)}}else(U=A(qc,O))?(O=U.h||O,fa=U.C?U.C:U.sign?"+"===K?1:-1:U.aa?!!fa:+K.replace(/,/,"."),"month"===U.h&&--fa,K=fa):K=p.V(O,K);F[O]=K}});return F}function f(x,z){Z(x)&&!y(A(v,"fromUTC"))&&
(v.fromUTC=!0);Z(x)&&!y(A(v,"setUTC"))&&(v.setUTC=!0);z&&(x=new Date(x.getTime()));return x}function g(){D(w,function(x){x.call()})}function h(x){x=x.toLowerCase();p=M.get(A(v,"locale"));for(var z=0,F,O;F=p.compiledFormats[z];z++)if(O=x.match(F.reg)){p.M(F,z);r=e(O,F);if(y(r.timestamp)){x=r.timestamp;r=null;break}y(r.ampm)&&(z=r.ampm,1===z&&12>r.hour?r.hour+=12:0===z&&12===r.hour&&(r.hour=0));if(r.utc||y(r.tzHour))if(z=r.tzHour,F=r.tzMinute,O=r.tzSign,Z(u,!0),z=(O||1)*(60*(z||0)+(F||0)))r.minute=
(r.minute||0)-z;y(r.shift)&&E(r.unit)&&(y(r.month)?r.unit=7:y(r.weekday)&&(r.unit=5));y(r.num)&&E(r.unit)&&(z=r.num,y(r.weekday)?m(z):y(r.month)&&(r.date=r.num));r.midday&&k(r.midday);y(r.day)&&(ka(u,3),E(r.unit)&&(r.unit=4,r.num=r.day,delete r.day));y(r.unit)&&(z=r.unit,F=y(r.num)?r.num:1,y(r.weekday)&&(6===z?(m(F),F=1):(Ia(u,{weekday:r.weekday},!0),delete r.weekday)),r.half&&(F*=r.half),y(r.shift)?F*=r.shift:r.sign&&(F*=r.sign),y(r.day)&&(F+=r.day,delete r.day),n(z),r[Sa.units[z]]=F,q=!0);r.edge&&
l(r.edge,r);r.yearSign&&(r.year*=r.yearSign);break}r?q?Ia(u,r,!1,1):(Z(u)&&ka(u,3),Ia(u,r,!0,0,A(v,"prefer"),t)):(u=new Date(x),A(v,"fromUTC")&&u.setTime(u.getTime()+6E4*u.getTimezoneOffset()));g();return u}function k(x){r.hour=x%24;23<x&&w.push(function(){Ra(u,"date",da(x/24))})}function l(x,z){var F=z.unit;F||$e(z,function(Ja,K,U,fa){"weekday"===Ja&&y(z.month)||(F=fa)});if(6===F&&y(z.weekday)){var O=z.weekday;delete z.weekday}w.push(function(){if(0>x)qb(u,F,A(v,"locale"));else if(0<x){if(1===x){var Ja=
4;qb(u,4)}Pb(u,F,A(v,"locale"),Ja)}y(O)&&(Ha(u,O,-x),ka(u,3))});z.specificity=6===F?4:F-1}function m(x){r.weekday=7*(x-1)+r.weekday;t=r.date=1}function n(x){var z;Ob(r,function(F,O,Ja,K){if(K>=x)return u.setTime(NaN),!1;K<x&&(z=z||{},z[F]=O,delete r[nc(r,F)])});z&&(w.push(function(){Ia(u,z,!0,!1,A(v,"prefer"),t)}),r.edge&&(l(r.edge,z),delete r.edge))}var p,q,t;var w=[];var v=function(x){x=H(x)?{locale:x}:x||{};x.prefer=+!!A(x,"future")-+!!A(x,"past");return x}(c);var u=a&&b?f(a,!0):Qa();Z(u,A(v,"fromUTC"));
if(H(b))u=h(b);else if(ha(b))u=f(b,J(v,"clone")||d);else if(T(b)){var r=na({},b);Ia(u,r,!0)}else(Q(b)||null===b)&&u.setTime(b);Z(u,!!A(v,"setUTC"));return{set:r,date:u}}function Ia(a,b,c,d,e,f){function g(){var l=wa[k];d=e;h(l.name,1,l,k)}function h(l,m,n,p){var q=n.method,t;e&&!k&&(k="weekday"===l?5:4===p?6:p+1);p>b.specificity||(b.specificity=p);if(t=m%1){if(p){var w=wa[ob(p)];t=nb(n.f/w.f*t);b[w.name]=t}m=da(m)}if("weekday"===l)d||Ha(a,m,f);else if(l=6===p&&28<pa(a),d&&!n.m)a.setTime(a.getTime()+
m*d*n.f);else{d&&(5===p&&(m*=7,q=wa[4].method),m=m*d+Y(a,q));n=q;p=m;q=d;"ISOWeek"===n?rd(a,p):ab(a,n,p,q);if(n=l)0>m&&(m=m%12+12),n=m%12!==ja(a);n&&va(a,0)}}var k;if(Q(b)&&d)b={millisecond:b};else if(Q(b))return a.setTime(b),a;Ob(b,h);c&&b.specificity&&ka(a,ob(b.specificity));a:{if(k&&!(7<k))switch(e){case -1:c=a>Qa();break a;case 1:c=a<Qa();break a}c=void 0}c&&g();return a}function Sb(a){var b=a.join("");return a&&a.length?b.length===a.length?"["+b+"]":Fa(a,$a).join("|"):""}function qa(a,b){1<a.length&&
(a="(?:"+a+")");b&&(a+="?");return a}function df(a,b,c){a=zd[a];return b=a.A?qa(b+qa(c)):a.J?b+qa(a.J+"|"+c):b+qa(c,!0)}function Ad(a,b,c,d){var e;1<c&&(e=a[b+(c-1)*d]);return e||a[b]}function Bd(a){function b(c){this.X(c)}b.prototype={H:function(c,d){return this.monthSuffix?c+1+this.monthSuffix:Ad(this.months,c,d,12)},I:function(c,d){return Ad(this.weekdays,c,d,7)},V:function(c,d){var e=this[c+"Map"],f;e&&(f=e[d]);E(f)&&(f=this.R(d),"month"===c&&--f);return f},R:function(c){var d=this.numeralMap[c];
if(y(d))return d;d=+c.replace(/,/,".");if(!isNaN(d))return d;d=this.S(c);isNaN(d)||(this.numeralMap[c]=d);return d},S:function(c){var d=1,e=0,f;var g=c.split("");for(var h=g.length-1;f=g[h];h--){c=A(this.numeralMap,f);E(c)&&(c=A(Pa,f)||0);(f=0<c&&0===c%10)?(k&&(e+=d),h?d=c:e+=c):(e+=c*d,d*=10);var k=f}return e},T:function(c){return this.ordinalSuffix||fd(c)},U:function(c,d){return this.F(c,d)},P:function(c){return this.F(cf(aa(0,c)),"duration")},s:function(){var c=this.firstDayOfWeek;return y(c)?
c:1},G:function(){return this.firstDayOfWeekYear||4},F:function(c,d){var e=c[0],f=c[1],g=c[2],h=this[d]||this.relative;if(X(h))return h.call(this,e,f,g,d);var k=this.units[8*(this.plural&&1!==e?1:0)+f]||this.units[f];var l=this[0<g?"fromNow":"ago"];return h.replace(/\{(.*?)\}/g,function(m,n){switch(n){case "num":return e;case "unit":return k;case "sign":return l}})},M:function(c,d){this.compiledFormats.splice(d,1);this.compiledFormats.unshift(c)},addFormat:function(c,d){function e(h){var k,l=h.match(/\?$/),
m=h.match(/^(\d+)\??$/),n=h.match(/(\d)(?:-(\d))?/),p=h.replace(/[^a-z]+$/i,"");if(k=A(g.parsingAliases,p))return h=f(k),l&&(h=qa(h,!0)),h;if(m)h=g.tokens[m[1]];else if(k=A(qc,p))h=k.src;else if(k=A(g.parsingTokens,p)||A(g,p),p=p.replace(/s$/,""),k||(k=A(g.parsingTokens,p)||A(g,p+"s")),H(k)){h=k;var q=g[p+"Suffix"]}else n&&(k=ic(k,function(t,w){var v=w%(g.units?8:k.length);return v>=n[1]&&v<=(n[2]||n[1])})),h=Sb(k);if(!h)return"";m?h=qa(h):(d.push(p),h="("+h+")");q&&(h=df(p,h,q));l&&(h+="?");return h}
function f(h){h=h.replace(/ /g," ?");return h.replace(/\{([^,]+?)\}/g,function(k,l){var m=l.split("|");return 1<m.length?qa(Fa(m,e).join("|")):e(l)})}var g=this;d||(d=[],c=f(c));g.addRawFormat(c,d)},addRawFormat:function(c,d){this.compiledFormats.unshift({reg:RegExp("^ *"+c+" *$","i"),to:d})},X:function(c){function d(l,m,n,p){var q=l,t=[];k[q]||(q+="s");if(!n){n={};var w=!0}e(q,function(v,u,r){u=u*m+r;r=p?p(r):r;n[v]=r;n[v.toLowerCase()]=r;t[u]=v});k[q]=t;w&&(k[l+"Map"]=n)}function e(l,m){D(k[l],
function(n,p){f(n,function(q,t){m(q,t,p)})})}function f(l,m){var n=Fa(l.split("+"),function(p){return p.replace(/(.+):(.+)$/,function(q,t,w){return Fa(w.split("|"),function(v){return t+v}).join("|")})}).join("|");D(n.split("|"),m)}function g(l,m,n){D(k[l],function(p){m&&(p=h(p,n));k.addFormat(p)})}function h(l,m){if(m)var n=qa("{time}[,\\s\\u3000]",!0)+l;else{n=",?[\\s\\u3000]";var p;(p=Sb(k.timeMarkers))&&(n+="| (?:"+p+") ");n=qa(n,k.timeMarkerOptional);n=qa(n+"{time}",!0);n=l+n}return n}var k=this;
k.compiledFormats=[];k.parsingAliases={};k.parsingTokens={};na(k,c);(function(){D(ef,function(l){var m=k[l];H(m)?k[l]=m.split(","):m||(k[l]=[])})})();d("month",12);d("weekday",7);d("unit",8);d("ampm",2);(function(){var l={};d("numeral",10,l);d("article",1,l,function(){return 1});d("placeholder",4,l,function(m){return Nb(10,m+1)});k.numeralMap=l})();k.parsingAliases.time=k.ampmFront?"{ampm?} {hour} (?:{minute} (?::?{second})?)?":k.ampm.length?"{hour}(?:[.:]{minute}(?:[.:]{second})? {ampm?}| {ampm})":
"{hour}(?:[.:]{minute}(?:[.:]{second})?)";k.parsingAliases.tzOffset="(?:{Z}|{GMT?}(?:{tzSign}{tzHour}(?::?{tzMinute}(?: \\([\\w\\s]+\\))?)?)?)?";(function(){B(zd,function(l,m){var n=l.i?qc[l.i].src:l.src;if(l.$||k.numeralUnits){var p="";var q=k.numerals.concat(k.placeholders).concat(k.articles);k.allowsFullWidth&&(q=q.concat(Cd.split("")));q.length&&(p="|(?:"+Sb(q)+")+");n+=p}(q=k[m+"s"])&&q.length&&(n+="|"+Sb(q));k.parsingTokens[m]=n})})();(function(){mc(function(l,m){var n=k.timeSuffixes[m];n&&
(k[(l.alias||l.name)+"Suffix"]=n)})})();(function(){D(k.modifiers,function(l){var m=l.name,n=m+"Map";var p=k[n]||{};f(l.src,function(q,t){var w=A(k.parsingTokens,m),v=l.value;p[q]=v;k.parsingTokens[m]=w?w+"|"+q:q;"sign"===l.name&&0===t&&(k[1===v?"fromNow":"ago"]=q)});k[n]=p})})();(function(){D(ff,function(l){var m=l.src;l.mdy&&k.mdy&&(m=l.mdy);l.time?(k.addFormat(h(m,!0)),k.addFormat(h(m))):k.addFormat(m)});k.addFormat("{time}")})();g("parse");g("timeParse",!0);g("timeFrontParse",!0,!0)}};return new b(a)}
function Tb(a,b){return jc(y(b)?b:" ",a)}function Dd(a,b,c,d,e){if(a.length<=b)return a.toString();d=E(d)?"...":d;switch(c){case "left":return a=e?sb(a,b,!0):a.slice(a.length-b),d+a;case "middle":c=xa(b/2);var f=bb(b/2);b=e?sb(a,c):a.slice(0,c);a=e?sb(a,f,!0):a.slice(a.length-f);return b+d+a;default:return b=e?sb(a,b):a.slice(0,b),b+d}}function tb(a,b,c){var d,e=[];if(X(b)){c=b;var f=/[\s\S]/g}else b?H(b)?f=RegExp($a(b),"gi"):Da(b)&&(f=RegExp(b.source,Za(b,"g"))):f=/[\s\S]/g;b=[];for(var g;null!=
(d=f.exec(a));)f.lastIndex===g?f.lastIndex+=1:b.push(d[0]),g=f.lastIndex;if(b)for(g=0,f=b.length;g<f;g++)if(d=b[g],e[g]=d,c)if(d=c.call(a,d,g,b),!1===d)break;else y(d)&&(e[g]=d);return e}function gf(a,b){return tb(a.trim(),/\S+/g,b)}function Ed(a,b){var c=Array(a.length),d;var e=0;for(d=a.length;e<d;e++){var f=a.charCodeAt(e);c[e]=f;b&&b.call(a,f,e,a)}return c}function ub(a){var b=N.acronyms&&N.acronyms.reg;return a.replace(/[-\s]+/g,"_").replace(b,function(c,d){return(0<d?"_":"")+c.toLowerCase()}).replace(/([A-Z\d]+)([A-Z][a-z])/g,
"$1_$2").replace(/([a-z\d])([A-Z])/g,"$1_$2").toLowerCase()}function hf(a,b){a=ub(a);return a.replace(jf,function(c,d,e,f){c=!1!==b||0<f;return(d=N.acronyms&&N.acronyms.find(e))&&c?d:c?rc(e,!0):e})}function rc(a,b,c){b&&(a=a.toLowerCase());return c?a.replace(kf,Ya):Ya(a)}function lf(a){var b=/[.:;!]$/,c;a=id(a);a=ub(a).replace(/_/g," ");return gf(a,function(d,e,f){d=N.human&&N.human.find(d)||d;d=N.acronyms&&N.acronyms.find(d)||d;var g=0==e;f=e==f.length-1;e=b.test(d);g=g||f||e||c;c=e;return g||-1===
gc(mf,d)?rc(d,!1,!0):d}).join(" ")}function sb(a,b,c){if(c)return sb(a.split("").reverse().join(""),b).split("").reverse().join("");var d=0;return ic(a.split(nf),function(e){d+=e.length;return d<=b}).join("")}function of(a){return a.replace(pf,function(b,c,d){return Fd[d]||V(c?parseInt(d,16):+d)})}function Gd(a,b,c){var d=0;H(b)?b=RegExp($a(b),"g"):b&&!b.global&&(b=RegExp(b.source,Za(b,"g")));if(c){var e=c;c=function(){var f=e[d++];return null!=f?f:""}}else c="";return a.replace(b,c)}function Hd(a,
b,c,d){b=H(b)?[b]:b;b=Fa(b||[],function(e){return $a(e)}).join("|");b=b.replace("all","")||"[^\\s>]+";return Id(a.toString(),RegExp("<(\\/)?("+b+")(\\s+[^<>]*?)?\\s*(\\/)?>","gi"),d,c)}function Id(a,b,c,d,e){function f(x,z,F,O,Ja){var K=a.slice(k,x),U="",fa="";H(d)?fa=d:d&&(fa=d.call(e,z,K,F,e)||"");c?U=fa:K=fa;K&&(K=Id(K,b,c,d,e));h+=U+K+(Ja?"":U);k=x+(O||0)}var g,h="",k=0,l=0;e=e||a;for(b=RegExp(b.source,"gi");g=b.exec(a);){var m=g[2],n=(g[3]||"").slice(1),p=!!g[1],q=!!g[4],t=g[0].length,w=-1!==
gc(qf,m.toLowerCase());q=!p&&!q&&!w;var v=m===u;u||(h+=a.slice(k,g.index),k=g.index);if(q)if(u)v&&l++;else{var u=m;var r=n;l++;k+=t}else p&&v?(l--,0===l&&(f(g.index,u,r,t,w),r=u=null)):u||f(g.index,m,n,t,w)}u&&f(a.length,u,r);return h+=a.slice(k)}function Jd(a,b,c){H(b)&&(b=a.indexOf(b),-1===b&&(b=c?a.length:0));return b}function Kd(a,b){var c;a&&a.constructor&&P(a.constructor.prototype)?c=b?db(a):a:T(a)||H(a)?c=Array.from(a):y(a)&&(c=[a]);return c||[]}function db(a){var b=Array(a.length);D(a,function(c,
d){b[d]=c});return b}function rf(a){var b=[];b.push(a);return b}function sf(a,b){var c=db(a),d=c.length;var e=P(b)?b:[b];c.length+=e.length;D(e,function(f,g){c[d+g]=f});return c}function Ld(a,b,c){c=+c;isNaN(c)&&(c=a.length);c=[c,0];y(b)&&(c=c.concat(b));a.splice.apply(a,c);return a}function Md(a,b){var c=[],d={},e=[];D(a,function(f,g){var h=b?Ea(f,b,a,[f,g,a]):f;h=Xa(h,e);J(d,h)||(c.push(f),d[h]=!0)});return c}function Nd(a,b,c){var d=[];b=b||Infinity;c=c||0;D(a,function(e){P(e)&&c<b?d=d.concat(Nd(e,
b,c+1)):d.push(e)});return d}function tf(a,b){return ic(a,function(c){return c||!b&&null!=c&&c.valueOf()===c.valueOf()})}function uf(a,b,c){var d={},e;D(a,function(f,g){e=Ea(f,b,a,[f,g,a]);J(d,e)||(d[e]=[]);d[e].push(f)});c&&B(d,c);return d}function Od(a,b,c){var d=[],e={},f=[];P(b)||(b=rf(b));D(b,function(g){e[Xa(g,f)]=!0});D(a,function(g){var h=Xa(g,f);J(e,h)!==c&&(delete e[h],d.push(g))});return d}function Pd(a,b){var c;if(H(a)&&H(b)){var d=eb("sortCollate");return d(a,b)}if(P(a)&&P(b)){if(a.length<
b.length)return-1;if(a.length>b.length)return 1;for(c=0;c<a.length;c++)if(d=Pd(a[c],b[c]),0!==d)return d;return 0}return a<b?-1:a>b?1:0}function Qd(a,b,c){H(a)||(a=String(a));c&&(a=a.toLowerCase());b&&(a=a.replace(b,""));return a}function Rd(a,b,c){a=a.charAt(b);return A(c,a)||a}function sc(a,b,c,d,e){if(P(a)){for(var f,g,h=[],k=0,l=a.length;k<l;k++)f=a[k],f=(g=d+(d&&b?"[]":""))||T(f)?sc(f,b,c,g,e):tc(f),h.push(f);d=h.join("&")}else T(a)&&a.toString===cc?d=vf(a,b,c,d,e):d?(a=c?c(a,d):ha(a)?a.getTime():
a,d=tc(d)+"="+tc(a)):d="";return d}function vf(a,b,c,d,e){var f=[];B(a,function(g,h){f.push(sc(g,b,c,d&&b?d+"["+h+"]":d?d+e+h:h,e))});return f.join("&")}function tc(a){return a||!1===a||0===a?encodeURIComponent(a):""}function wf(a,b){var c=String(a||"").replace(/^.*?\?/,""),d={},e;b=b||{};c&&D(c.split("&"),function(f){f=f.split("=");var g=decodeURIComponent(f[0]);f=2===f.length?decodeURIComponent(f[1]):"";e=!1!==b.auto;var h=g,k=b.deep;g=e;var l=b.separator,m=b.transform,n;if(l){h=h.split(l);k=h[0];
for(var p=1,q=h.length;p<q;p++)k+="["+h[p]+"]";h=k;k=!0}!0===k&&(n=h.match(xf))?yf(d,n,f,k,g,l,m):Sd(d,h,f,g,m)});return d}function yf(a,b,c,d,e,f,g){var h=b[1];b=b[2].slice(1,-1).split("][");D(b,function(k){J(a,h)||(a[h]=k?{}:[]);a=A(a,h);h=k?k:a.length.toString()});Sd(a,h,c,e,g)}function Sd(a,b,c,d,e){var f;e&&(f=e(c,b,a));y(f)?c=f:d&&(c=zf(a,b,c));a[b]=c}function zf(a,b,c){if(c){if("true"===c)return!0;if("false"===c)return!1}else return null;var d=+c;if(!isNaN(d)&&""!==c&&!Af.test(c))return d;
a=A(a,b);return c&&a?P(a)?a.concat(c):[a,c]:c}function uc(a,b,c){c=c||{};return Ub(a,b,c.deep,c.resolve,c.hidden,c.descriptor)}function vc(a,b,c){P(b)||(b=[b]);D(b,function(d){return uc(a,d,c)});return a}function Bf(a,b,c){wc&&a?Td(wc,b,c,a):B(b,c);Ud&&Td(Ud,b,c,a)}function Td(a,b,c,d){a=a(b);for(var e,f=0,g;g=a[f];f++)e=Vd(b,g),(e.enumerable||d)&&c(b[g],g)}function Ub(a,b,c,d,e,f){var g=X(d),h=!1!==d;E(a)?a=Wd(b):h&&ha(a)&&ha(b)&&a.setTime(b.getTime());if(Ca(a))return b;Ca(b)&&(b=lb(b));Bf(e,b,function(k,
l){var m=b[l];var n=A(a,l);if(g){var p=d(l,n,m,a,b);if(E(p))return;if(y(p)&&p!==C){m=p;var q=!0}}else if(E(m))return;if((q=!q&&c&&T(m)&&!Da(m))||h||!y(n))q&&(m=Ub(n,m,c,d,e,f)),wc&&f?(n=a,q=Vd(b,l),y(q.value)&&(q.value=m),Eb(n,l,q)):a[l]=m});return a}function Wd(a){var b=ia(a);if(P(a,b))return[];if(Gb(a,b))return{};if(ha(a,b))return new Date(a.getTime());if(Da(a,b))return RegExp(a.source,Za(a));if(Ca(a&&a.valueOf()))return a;throw new TypeError("Must be a basic data type");}function xc(a,b){var c=
Wd(a);return Ub(c,a,b,!0,!0,!0)}function Cf(a){var b=[];B(a,function(c){b.push(c)});return b}function Df(a,b){var c=b;X(b)||(c=function(){if(b)a[b]()});c.call(a,a);return a}function Xd(a,b,c){var d,e={};b=[].concat(b);B(a,function(f,g){d=!1;for(var h=0;h<b.length;h++){var k=b[h],l=g;(Da(k)?k.test(l):T(k)?l in k:l===String(k))&&(d=!0)}d===c&&(e[g]=f)});return e}function Ef(a,b){var c=ta(b);B(a,function(d,e){c(d,e,a)&&delete a[e]});return a}function Ff(a,b){var c={},d=ta(b);B(a,function(e,f){d(e,f,
a)||(c[f]=e)});return c}function Yd(a,b,c){if(!T(a))return c?a:{};b=lb(b);return Ub({},a,!1,function(d,e,f){if((d in b&&Oa(f,b[d]))!==c)return f})}function Zd(a,b){var c=0;vb(a,b,function(d){c+=d});return c}function $d(a,b){var c=0,d=0;vb(a,b,function(e){c+=e;d++});return c/(d||1)}function ae(a,b){var c=[];vb(a,b,function(f){c.push(f)});var d=c.length;if(!d)return 0;c.sort(function(f,g){return(f||0)-(g||0)});var e=da(d/2);return d%2?c[e]:(c[e-1]+c[e])/2}function wb(a,b,c,d,e){var f=[],g,h;if(fb(b)){var k=
b;b=c}vb(a,b,function(l,m){if(E(l))throw new TypeError("Cannot compare with undefined");g=e?m:a[m];if(l===h)f.push(g);else if(E(h)||d&&l>h||!d&&l<h)f=[g],h=l});return be(f,a,k,e)}function Vb(a,b,c,d,e){var f={},g=[];if(fb(b)){var h=b;b=c}vb(a,b,function(l,m){var n=Xa(l,g),p=A(f,n)||[];p.push(e?m:a[m]);f[n]=p});d=wb(f,!!h,"length",d,!0);if(h){var k=[];B(d,function(l){k=k.concat(l)})}else k=A(f,d);return be(k,a,h,e)}function be(a,b,c,d){if(d&&c)return a.reduce(function(e,f){e[f]=b[f];return e},{});
a&&!c&&(a=a[0]);return a}function vb(a,b,c){var d=P(a);B(a,function(e,f){if(d){if(f>>>0!=f||4294967295==f)return;f=+f}var g=Ea(e,b,a,[e,f,a]);c(g,f)})}function ce(a,b){if(X(a))return a;if(a)return function(c,d,e){return Ea(c,a,b,[c,d,e])}}function Ka(a){if(X(a))return a;var b=ta(a);return function(c,d,e){return b(c,d,e)}}function gb(a,b){var c=Array.prototype[a];return function(d,e,f,g){var h=Array(2);Yc(0<g);h[0]=b(e,f);h[1]=f;return c.apply(d,h)}}function Gf(a,b){Ba(b);B(a,function(c,d){b(c,d,a)});
return a}function Hf(a,b){var c={};B(a,function(d,e){c[e]=Ea(d,b,a,[d,e,a])});return c}function If(a,b,c){var d=y(c);B(a,function(e,f){d?c=b(c,e,f,a):(c=e,d=!0)});return c}function Jf(a,b){var c=ta(b),d={};B(a,function(e,f){c(e,f,a)&&(d[f]=e)});return d}function Kf(a,b){var c=ta(b),d=0;B(a,function(e,f){c(e,f,a)&&d++});return d}function yc(a){var b=Array.prototype[a];return function(c,d){var e=ta(d);return b.call(Object.keys(c),function(f){return e(c[f],f,c)})}}function zc(a,b,c,d){var e=a.toFixed(20),
f=e.search(/\./);e=e.search(/[1-9]/);f-=e;0<f&&--f;e=c.split(",");1===e.length&&(e=c.split(""));var g=e.indexOf("|");-1===g&&(g="_"===e[0]?0:e.length);var h=aa(La(bb(f/3),e.length-g-1),-g);for(c=e[h+g];"_"===c;)h+=0>h?-1:1,c=e[h+g];"|"===c&&(c="");-9>f&&(b=oa(f)-9);d=d?Nb(2,10*h):Nb(10,3*h);return de(mb(a/d,b||0))+c}function de(a,b){var c="";var d=ee("decimal");var e=ee("thousands");var f=Q(b)?mb(a,b||0).toFixed(aa(b,0)):a.toString();f=f.replace(/^-/,"");var g=f.split(".");var h=g[0];g=g[1];if(/e/.test(f))c=
f;else for(f=h.length;0<f;f-=3)f<h.length&&(c=e+c),c=h.slice(aa(0,f-3),f)+c;g&&(c+=d+jc("0",(b||0)-g.length)+g);return(0>a?"-":"")+c}function Ac(a){return function(b,c){return c?mb(b,c,a):a(b)}}function hb(a,b,c,d,e){b=Va(b||0);Wb(a)||Wb(a,[]);Bc(a,!1);Wb(a).push(setTimeout(function(){Bc(a)||c.apply(d,e||[])},b))}function fe(a){var b=Wb(a),c;if(P(b))for(;c=b.shift();)clearTimeout(c);Bc(a,!0);return a}function ge(a,b,c,d){function e(){if(f.length<d-(g&&c?1:0)){for(var n=[],p=0,q=arguments.length;p<
q;p++)n.push(arguments[p]);f.push([this,n])}g||(g=!0,c?m():hb(e,k,m));return h}var f=[],g=!1,h;b=b||1;d=d||Infinity;var k=xa(b);var l=nb(k/b)||1;var m=function(){var n=f.length,p;if(0!=n){for(p=aa(n-l,0);n>p;)h=Function.prototype.apply.apply(a,f.shift()),n--;hb(e,k,function(){g=!1;m()})}};return e}function Lf(){for(var a=arguments,b=a.length,c=Array(b);b--;)c[b]=a[b];return c}function Mf(a,b,c){var d={},e=[],f=0;return function(){var g=b.apply(this,arguments);g=Xa(g,e);if(J(d,g))return A(d,g);f===
c&&(d={},e=[],f=0);f++;return d[g]=a.apply(this,arguments)}}function ca(a,b){this.start=Cc(a);this.end=Cc(b)}function he(a){return H(a)?a.charCodeAt(0):a}function ie(a){return null==a?a:ha(a)?a.getTime():a.valueOf()}function je(a){a=a.toString().split(".");return a[1]?a[1].length:0}function Nf(a,b){return aa(je(a),je(b))}function Cc(a){return ha(a)?new Date(a.getTime()):ie(a)}function ke(a){var b=ie(a);return(!!b||0===b)&&-Infinity!==a&&Infinity!==a}function Xb(a){return ke(a.start)&&ke(a.end)&&typeof a.start===
typeof a.end}function Yb(a,b,c,d){var e=a.start,f=a.end,g=f<e,h=e,k=0,l=[];if(!Xb(a))return c?NaN:[];X(b)&&(d=b,b=null);b=b||1;if(Q(e)){var m=Nf(e,b);var n=function(){return mb(h+b,m)}}else if(H(e))n=function(){return V(h.charCodeAt(0)+b)};else if(ha(e)){n=le(b);b=n[0];var p=n[1];n=function(){return me(h,b,p)}}for(g&&0<b&&(b*=-1);g?h>=f:h<=f;)c||l.push(h),d&&d(h,k,a),h=n(),k++;return c?k-1:l}function le(a){if(Q(a))return[a,"Milliseconds"];var b=a.match(Of);a=+b[1]||1;b=Ya(b[2].toLowerCase());b.match(/hour|minute|second/i)?
b+="s":"Year"===b?b="FullYear":"Week"===b?(b="Date",a*=7):"Day"===b&&(b="Date");return[a,b]}function me(a,b,c){var d=ne[c];d?d=new Date(a.getTime()+b*d):(d=new Date(a),ab(d,c,Y(a,c)+b));return d}function Dc(a,b){var c=a.start,d=a.end,e=d<c?d:c;c=c>d?c:d;return Cc(b<e?e:b>c?c:b)}function ib(a){return ha(a)?a:null==a?new Date:W.create?W.create(a):new Date(a)}function I(a,b){b=b||a;xb("plural",a,b);H(a)&&G(b,a)}function G(a,b){xb("singular",a,b)}function za(a,b){var c=RegExp(a+"$","i"),d=RegExp(b+"$",
"i");I(c,b);I(d,b);G(d,a);G(c,a)}function Pf(a){D(ra(a),function(b){I(b)})}function oe(a,b){xb("human",a,b)}function Qf(){var a=[];B(N.acronyms.map,function(b,c){c===b&&a.push(b)});a.sort(function(b,c){return c.length-b.length});N.acronyms.reg=RegExp("\\b"+a.join("|")+"\\b","g")}function xb(a,b,c){N[a]||(N[a]=new Ec);N[a].add(b,c)}function Fc(a,b,c,d){var e=Zb[d];b=(b||"").replace(/all/,"").replace(/(\w)lphabet|umbers?|atakana|paces?|unctuation/g,"$1");return a.replace(c,function(f){var g=e[f],h;
if(g){if(""===b&&g.all)return g.all;for(var k=0,l=b.length;k<l;k++)if(h=g[b.charAt(k)])return h}return f})}var C,Ta="undefined"!==typeof global&&global.Object===Object?global:this,Rf="undefined"!==typeof module&&module.O,Qc=!1,Cb={},Rc={},Eb=Object.defineProperty&&Object.defineProperties?Object.defineProperty:Ge,Tc=Pc("Chainable"),Uc=Object.getOwnPropertyNames,cc=Object.prototype.toString,He=Object.prototype.hasOwnProperty;(function(){C=Ta.Sugar;if(!C){C=function(a){B(C,function(b,c){J(Cb,c)&&b.extend(a)});
return C};if(Rf)module.O=C;else try{Ta.Sugar=C}catch(a){}B("Object Number String Array Date RegExp Function".split(" "),function(a){Oc(a)});L(C,"extend",C);L(C,"toString",Be);L(C,"createNamespace",Oc);L(C,"util",{hasOwn:J,getOwn:A,setProperty:L,classToString:ia,defineProperty:Eb,forEachProperty:B,mapNativeToChainable:Db})}})();var Qe=!("0"in Object("a")),Pe=/^(.*?)\[([-\d]*)\.\.([-\d]*)\](.*)$/,Te=/([{}])\1|\{([^}]*)\}|(%)%|(%(\w*))/g,jb=C.Object,la=C.Array,W=C.Date,ma=C.String,Aa=C.Number,Gc=C.Function,
pe=C.RegExp;J=C.util.hasOwn;A=C.util.getOwn;L=C.util.setProperty;ia=C.util.classToString;Eb=C.util.defineProperty;B=C.util.forEachProperty;Db=C.util.mapNativeToChainable;var Jb,fb,Q,H,ha,Da,X,P,Kb,Lb,Mb,qe=Na("alias"),Ma=Na("defineStatic"),S=Na("defineInstance"),Hc=Na("defineStaticPolyfill"),$b=Na("defineInstancePolyfill"),dc=Na("defineInstanceAndStatic"),yb=Na("defineInstanceWithArguments"),da=Math.trunc||function(a){return 0!==a&&isFinite(a)?0>a?xa(a):bb(a):a},gd,Pa,Cd,oa=Math.abs,Nb=Math.pow,La=
Math.min,aa=Math.max,xa=Math.ceil,bb=Math.floor,nb=Math.round,V=String.fromCharCode,N={},Z=kb("utc"),Ve=1E3;(function(){function a(g){f["[object "+g+"]"]=!0}function b(g,h){return h&&Fb(new h,"Object")?c(h):d(g)}function c(g){var h=String(g);return function(k){return String(k.constructor)===h}}function d(g){return function(h,k){return Fb(h,g,k)}}function e(g){var h=g.toLowerCase();return function(k){var l=typeof k;return l===h||"object"===l&&Fb(k,g)}}var f={};(function(){var g=ra("Boolean Number String Date RegExp Function Array Error Set Map");
fb=e(g[0]);Q=e(g[1]);H=e(g[2]);ha=b(g[3]);Da=b(g[4]);X=b(g[5]);P=Array.isArray||b(g[6]);Mb=b(g[7]);Kb=b(g[8],"undefined"!==typeof Set&&Set);Lb=b(g[9],"undefined"!==typeof Map&&Map);a("Arguments");a(g[0]);a(g[1]);a(g[2]);a(g[3]);a(g[4]);a(g[6])})();(function(){D(ra("Int8 Uint8 Uint8Clamped Int16 Uint16 Int32 Uint32 Float32 Float64"),function(g){a(g+"Array")})})();Jb=function(g,h){h=h||ia(g);return f[h]||Gb(g,h)}})();(function(){var a="";Pa={};for(var b=0,c;9>=b;b++)c=V(b+65296),a+=c,Pa[c]=V(b+48);
Pa[","]="";Pa["\uff0e"]=".";Pa["."]=".";gd=RegExp("["+(a+"\uff0e,.]"),"g");Cd=a})();var Sf="valueOf toString constructor isPrototypeOf hasOwnProperty toLocaleString propertyIsEnumerable".split(" ");(function(){if(!{toString:1}.propertyIsEnumerable("toString")){var a=B;B=function(b,c){a(b,c);for(var d=0,e;(e=Sf[d])&&(!J(b,e)||!1!==c.call(b,b[e],e,b));d++);}}})();Object.getOwnPropertyNames||We();Hc(jb,{keys:function(a){var b=[];if(null==a)throw new TypeError("Object required");B(lb(a),function(c,d){b.push(d)});
return b}});Hc(la,{isArray:function(a){return P(a)}});$b(la,{every:function(a){var b=arguments[1],c=this.length,d=0;for(Ba(a);d<c;){if(d in this&&!a.call(b,this[d],d,this))return!1;d++}return!0},some:function(a){var b=arguments[1],c=this.length,d=0;for(Ba(a);d<c;){if(d in this&&a.call(b,this[d],d,this))return!0;d++}return!1},map:function(a){var b=arguments[1],c=this.length,d=0,e=Array(c);for(Ba(a);d<c;)d in this&&(e[d]=a.call(b,this[d],d,this)),d++;return e},filter:function(a){var b=arguments[1],
c=this.length,d=0,e=[];for(Ba(a);d<c;)d in this&&a.call(b,this[d],d,this)&&e.push(this[d]),d++;return e},indexOf:function(a){var b=arguments[1];return H(this)?this.indexOf(a,b):jd(this,a,b)},lastIndexOf:function(a){var b=arguments[1];return H(this)?this.lastIndexOf(a,b):jd(this,a,b,!0)},forEach:function(a){var b=arguments[1],c=this.length,d=0;for(Ba(a);d<c;)d in this&&a.call(b,this[d],d,this),d++},reduce:function(a){return kd(this,a,arguments[1])},reduceRight:function(a){return kd(this,a,arguments[1],
!0)}});var Tf=RegExp("^[\t\n\x0B\f\r \u00a0\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u2028\u2029\u3000\ufeff]+|[\t\n\x0B\f\r \u00a0\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u2028\u2029\u3000\ufeff]+$","g");$b(ma,{trim:function(){return this.toString().replace(Tf,"")}});$b(Gc,{bind:function(a){for(var b=[],c=1,d=arguments.length;c<d;c++)b.push(arguments[c]);var e=this;Ba(this);c=function(){for(var f=[],
g=0,h=arguments.length;g<h;g++)f.push(arguments[g]);return e.apply(e.prototype&&this instanceof e?this:a,b.concat(f))};c.prototype=this.prototype;return c}});Hc(W,{now:function(){return(new Date).getTime()}});$b(W,{toISOString:function(){return ea(this.getUTCFullYear(),4)+"-"+ea(this.getUTCMonth()+1,2)+"-"+ea(this.getUTCDate(),2)+"T"+ea(this.getUTCHours(),2)+":"+ea(this.getUTCMinutes(),2)+":"+ea(this.getUTCSeconds(),2)+"."+ea(this.getUTCMilliseconds(),3)+"Z"},toJSON:function(a){return this.toISOString(a)}},
!function(){var a=new Date(Date.UTC(2E3,0));return!!a.toISOString&&"2000-01-01T00:00:00.000Z"===a.toISOString()}());var ef="months weekdays units numerals placeholders articles tokens timeMarkers ampm timeSuffixes parse timeParse timeFrontParse modifiers".split(" "),Uf=/(\w{3})[()\s\d]*$/,qc={yyyy:{h:"year",src:"\\d{4}"},MM:{h:"month",src:"[01]?\\d"},dd:{h:"date",src:"[0123]?\\d"},hh:{h:"hour",src:"[0-2]?\\d"},mm:{h:"minute",src:"[0-5]\\d"},ss:{h:"second",src:"[0-5]\\d(?:[,.]\\d+)?"},yy:{h:"year",
src:"\\d{2}"},y:{h:"year",src:"\\d"},yearSign:{src:"[+-]",sign:!0},tzHour:{src:"[0-1]\\d"},tzMinute:{src:"[0-5]\\d"},tzSign:{src:"[+\u2212-]",sign:!0},ihh:{h:"hour",src:"[0-2]?\\d(?:[,.]\\d+)?"},imm:{h:"minute",src:"[0-5]\\d(?:[,.]\\d+)?"},GMT:{h:"utc",src:"GMT",C:1},Z:{h:"utc",src:"Z",C:1},timestamp:{src:"\\d+"}},zd={year:{i:"yyyy",A:!0},month:{i:"MM",A:!0},date:{i:"dd",A:!0},hour:{i:"hh",J:":"},minute:{i:"mm"},second:{i:"ss"},num:{src:"\\d+",$:!0}},ff=[{src:"{MM}[-.\\/]{yyyy}"},{time:!0,src:"{dd}[-.\\/]{MM}(?:[-.\\/]{yyyy|yy|y})?",
mdy:"{MM}[-.\\/]{dd}(?:[-.\\/]{yyyy|yy|y})?"},{time:!0,src:"{yyyy}[-.\\/]{MM}(?:[-.\\/]{dd})?"},{src:"\\\\/Date\\({timestamp}(?:[+-]\\d{4,4})?\\)\\\\/"},{src:"{yearSign?}{yyyy}(?:-?{MM}(?:-?{dd}(?:T{ihh}(?::?{imm}(?::?{ss})?)?)?)?)?{tzOffset?}"}],wd={ISO8601:"{yyyy}-{MM}-{dd}T{HH}:{mm}:{ss}.{SSS}{Z}",RFC1123:"{Dow}, {dd} {Mon} {yyyy} {HH}:{mm}:{ss} {ZZ}",RFC1036:"{Weekday}, {dd}-{Mon}-{yy} {HH}:{mm}:{ss} {ZZ}"},Vf=[{b:"Dow",a:"a",j:"dow",get:function(a,b){return M.get(b).I(R(a),2)}},{b:"Weekday",
a:"A",j:"weekday",D:!0,get:function(a,b,c){return M.get(b).I(R(a),c)}},{b:"Mon",a:"b h",j:"mon",get:function(a,b){return M.get(b).H(ja(a),2)}},{b:"Month",a:"B",j:"month",D:!0,get:function(a,b,c){return M.get(b).H(ja(a),c)}},{a:"C",get:function(a){return ua(a).toString().slice(0,2)}},{b:"d date day",a:"d",g:2,c:"dd",l:"do",get:function(a){return pa(a)}},{a:"e",get:function(a){return ea(pa(a),2,!1,10," ")}},{b:"H 24hr",a:"H",g:2,c:"HH",get:function(a){return Y(a,"Hours")}},{b:"h hours 12hr",a:"I",g:2,
c:"hh",get:function(a){return Y(a,"Hours")%12||12}},{b:"D",a:"j",g:3,c:"DDD",get:function(a){var b=ka(Ga(a),6);return Qb(a,b,wa[4])+1}},{b:"M",a:"m",g:2,l:"Mo",c:"MM",get:function(a){return ja(a)+1}},{b:"m minutes",a:"M",g:2,c:"mm",get:function(a){return Y(a,"Minutes")}},{b:"Q",get:function(a){return xa((ja(a)+1)/3)}},{b:"TT",a:"p",get:function(a,b){return oc(a,b)}},{b:"tt",a:"P",get:function(a,b){return oc(a,b).toLowerCase()}},{b:"T",j:"t",get:function(a,b){return oc(a,b).charAt(0)}},{b:"s seconds",
a:"S",g:2,c:"ss",get:function(a){return Y(a,"Seconds")}},{b:"S ms",g:3,c:"SSS",get:function(a){return Y(a,"Milliseconds")}},{b:"e",a:"u",l:"eo",get:function(a){return R(a)||7}},{a:"U",g:2,get:function(a){return cb(a,!1,0)}},{b:"W",a:"V",g:2,l:"Wo",c:"WW",get:function(a){return cb(a,!0)}},{a:"w",get:function(a){return R(a)}},{b:"w",l:"wo",c:"ww",get:function(a,b){var c=M.get(b),d=c.s(b);return cb(a,!0,d,c.G(b))}},{a:"W",g:2,get:function(a){return cb(a,!1)}},{c:"gggg",u:"gg",get:function(a,b){return sd(a,
b)}},{a:"G",g:4,B:"g",c:"GGGG",u:"GG",get:function(a,b){return sd(a,b,!0)}},{b:"year",c:"yyyy",u:"yy",a:"Y",g:4,B:"y",get:function(a){return ua(a)}},{b:"ZZ",a:"z",get:function(a){return lc(a)}},{b:"X",get:function(a){return da(a.getTime()/1E3)}},{b:"x",get:function(a){return a.getTime()}},{b:"Z",get:function(a){return lc(a,!0)}},{b:"z",a:"Z",get:function(a){return(a=a.toString().match(Uf))?a[1]:""}},{a:"D",alias:"%m/%d/%y"},{a:"F",alias:"%Y-%m-%d"},{a:"r",alias:"%I:%M:%S %p"},{a:"R",alias:"%H:%M"},
{a:"T",alias:"%H:%M:%S"},{a:"x",alias:"{short}"},{a:"X",alias:"{time}"},{a:"c",alias:"{stamp}"}],wa=[{name:"millisecond",method:"Milliseconds",f:1,start:0,end:999},{name:"second",method:"Seconds",f:1E3,start:0,end:59},{name:"minute",method:"Minutes",f:6E4,start:0,end:59},{name:"hour",method:"Hours",f:36E5,start:0,end:23},{name:"day",alias:"date",method:"Date",m:!0,f:864E5,start:1,end:function(a){return md(a)}},{name:"week",method:"ISOWeek",m:!0,f:6048E5},{name:"month",method:"Month",m:!0,f:26298E5,
start:0,end:11},{name:"year",method:"FullYear",m:!0,f:315576E5,start:0}],Ye=ec(W,{newDateInternal:function(){return new Date}}),ba,zb,Rb,Sa,M;Ma(W,{create:function(a,b){return ya(a,b)},getLocale:function(a){return M.get(a,!a)},getAllLocales:function(){return M.getAll()},getAllLocaleCodes:function(){return Object.keys(M.getAll())},setLocale:function(a){return M.set(a)},addLocale:function(a,b){return M.add(a,b)},removeLocale:function(a){return M.remove(a)}});yb(W,{set:function(a,b){b=nd(b);return Ia(a,
b[0],b[1])},advance:function(a,b){return pd(a,b,1)},rewind:function(a,b){return pd(a,b,-1)}});S(W,{get:function(a,b,c){return rb(a,b,c,void 0).date},setWeekday:function(a,b){return Ha(a,b)},setISOWeek:function(a,b){return rd(a,b)},getISOWeek:function(a){return cb(a,!0)},beginningOfISOWeek:function(a){var b=R(a);0===b?b=-6:1!==b&&(b=1);Ha(a,b);return ka(a,3)},endOfISOWeek:function(a){0!==R(a)&&Ha(a,7);return Pb(a,4)},getUTCOffset:function(a,b){return lc(a,b)},setUTC:function(a,b){return Z(a,b)},isUTC:function(a){return!!Z(a)||
0===a.getTimezoneOffset()},isValid:function(a){return!isNaN(a.getTime())},isAfter:function(a,b,c){return a.getTime()>ya(b).getTime()-(c||0)},isBefore:function(a,b,c){return a.getTime()<ya(b).getTime()+(c||0)},isBetween:function(a,b,c,d){a=a.getTime();b=ya(b).getTime();var e=ya(c).getTime();c=La(b,e);b=aa(b,e);d=d||0;return c-d<=a&&b+d>=a},isLeapYear:function(a){a=ua(a);return 0===a%4&&0!==a%100||0===a%400},daysInMonth:function(a){return md(a)},format:function(a,b,c){return ud(a,b,c)},relative:function(a,
b,c){return td(a,null,b,c)},relativeTo:function(a,b,c){return td(a,ya(b),c)},is:function(a,b,c){return xd(a,b,c)},reset:function(a,b,c){b=b?af(b):4;qb(a,b,c);return a},clone:function(a){return Ga(a)},iso:function(a){return a.toISOString()},getWeekday:function(a){return R(a)},getUTCWeekday:function(a){return a.getUTCDay()}});S(Aa,{duration:function(a,b){return M.get(b).P(a)}});var Ic={code:"en",plural:!0,timeMarkers:"at",ampm:"AM|A.M.|a,PM|P.M.|p",units:"millisecond:|s,second:|s,minute:|s,hour:|s,day:|s,week:|s,month:|s,year:|s",
months:"Jan:uary|,Feb:ruary|,Mar:ch|,Apr:il|,May,Jun:e|,Jul:y|,Aug:ust|,Sep:tember|t|,Oct:ober|,Nov:ember|,Dec:ember|",weekdays:"Sun:day|,Mon:day|,Tue:sday|,Wed:nesday|,Thu:rsday|,Fri:day|,Sat:urday|+weekend",numerals:"zero,one|first,two|second,three|third,four:|th,five|fifth,six:|th,seven:|th,eight:|h,nin:e|th,ten:|th",articles:"a,an,the",tokens:"the,st|nd|rd|th,of|in,a|an,on",time:"{H}:{mm}",past:"{num} {unit} {sign}",future:"{num} {unit} {sign}",duration:"{num} {unit}",modifiers:[{name:"half",
src:"half",value:.5},{name:"midday",src:"noon",value:12},{name:"midday",src:"midnight",value:24},{name:"day",src:"yesterday",value:-1},{name:"day",src:"today|tonight",value:0},{name:"day",src:"tomorrow",value:1},{name:"sign",src:"ago|before",value:-1},{name:"sign",src:"from now|after|from|in|later",value:1},{name:"edge",src:"first day|first|beginning",value:-2},{name:"edge",src:"last day",value:1},{name:"edge",src:"end|last",value:2},{name:"shift",src:"last",value:-1},{name:"shift",src:"the|this",
value:0},{name:"shift",src:"next",value:1}],parse:"(?:just)? now;{shift} {unit:5-7};{months?} (?:{year}|'{yy});{midday} {4?} {day|weekday};{months},?(?:[-.\\/\\s]{year})?;{edge} of (?:day)? {day|weekday};{0} {num}{1?} {weekday} {2} {months},? {year?};{shift?} {day?} {weekday?} {timeMarker?} {midday};{sign?} {3?} {half} {3?} {unit:3-4|unit:7} {sign?};{0?} {edge} {weekday?} {2} {shift?} {unit:4-7?} {months?},? {year?}".split(";"),timeParse:"{day|weekday};{shift} {unit:5?} {weekday};{0?} {date}{1?} {2?} {months?};{weekday} {2?} {shift} {unit:5};{0?} {num} {2?} {months}\\.?,? {year?};{num?} {unit:4-5} {sign} {day|weekday};{year}[-.\\/\\s]{months}[-.\\/\\s]{date};{0|months} {date?}{1?} of {shift} {unit:6-7};{0?} {num}{1?} {weekday} of {shift} {unit:6};{date}[-.\\/\\s]{months}[-.\\/\\s](?:{year}|'?{yy});{weekday?}\\.?,? {months}\\.?,? {date}{1?},? (?:{year}|'{yy})?".split(";"),
timeFrontParse:["{sign} {num} {unit}","{num} {unit} {sign}","{4?} {day|weekday}"]},re=na(na({},Ic),{mdy:!0,firstDayOfWeek:0,firstDayOfWeekYear:1,"short":"{MM}/{dd}/{yyyy}",medium:"{Month} {d}, {yyyy}","long":"{Month} {d}, {yyyy} {time}",full:"{Weekday}, {Month} {d}, {yyyy} {time}",stamp:"{Dow} {Mon} {d} {yyyy} {time}",time:"{h}:{mm} {TT}"}),se=na(na({},Ic),{"short":"{dd}/{MM}/{yyyy}",medium:"{d} {Month} {yyyy}","long":"{d} {Month} {yyyy} {H}:{mm}",full:"{Weekday}, {d} {Month}, {yyyy} {time}",stamp:"{Dow} {d} {Mon} {yyyy} {time}"}),
Wf=na(na({},Ic),{"short":"{yyyy}-{MM}-{dd}",medium:"{d} {Month}, {yyyy}","long":"{d} {Month}, {yyyy} {H}:{mm}",full:"{Weekday}, {d} {Month}, {yyyy} {time}",stamp:"{Dow} {d} {Mon} {yyyy} {time}"}),te={"en-US":re,"en-GB":se,"en-AU":se,"en-CA":Wf};(function(){function a(b){this.o={};this.add(b)}a.prototype={get:function(b,c){var d=this.o[b];!d&&te[b]?d=this.add(b,te[b]):!d&&b&&(d=this.o[b.slice(0,2)]);return d||!1===c?d:this.current},getAll:function(){return this.o},set:function(b){var c=this.get(b,
!1);if(!c)throw new TypeError("Invalid Locale: "+b);return this.current=c},add:function(b,c){c?c.code=b:(c=b,b=c.code);var d=c.compiledFormats?c:Bd(c);this.o[b]=d;this.current||(this.current=d);return d},remove:function(b){this.current.code===b&&(this.current=this.get("en"));return delete this.o[b]}};Sa=Bd(re);M=new a(Sa)})();(function(){function a(k,l,m){l&&D(ra(l),function(n){k[n]=m})}function b(k){return function(l,m){return k(l,m).toLowerCase()}}function c(k){return function(l,m){var n=k(l,m);
return n+M.get(m).T(n)}}function d(k,l){return function(m,n){return ea(k(m,n),l)}}function e(k){return function(l,m){return k(l,m)%100}}function f(k){return function(l,m){return Rb(k,l,m)}}function g(k,l){function m(n,p){return k.get(n,p,l)}a(ba,k.b+l,m);k.j&&(ba[k.j+l]=b(m))}function h(k){return function(l,m){var n=M.get(m);return Rb(n[k],l,m)}}ba={};zb={};D(Vf,function(k){var l=k.get,m;k.j&&(ba[k.j]=b(l));k.l&&(ba[k.l]=c(l,k));k.c&&(ba[k.c]=d(l,k.c.length));k.u&&(ba[k.u]=d(e(l),2));k.B&&(zb[k.B]=
d(e(l),2));k.g&&(m=d(l,k.g));k.alias&&(l=f(k.alias));if(k.D)for(var n=1;5>=n;n++)g(k,n);a(ba,k.b,l);a(zb,k.a,m||l)});B(wd,function(k,l){a(ba,l,f(k))});Ua(W,"short medium long full",function(k,l){var m=h(l);a(ba,l,m);k[l]=m});a(ba,"time",h("time"));a(ba,"stamp",h("stamp"))})();(function(){Rb=hd(function(a,b,c){return A(ba,b)(a,c)},function(a,b,c){return A(zb,b)(a,c)},function(a,b){return J(ba,a)||J(zb,b)})})();(function(){Ua(W,wa,function(a,b,c){var d=b.name,e=Ya(d);4<c&&D(["Last","This","Next"],function(f){a["is"+
f+e]=function(g,h){return yd(g,f+" "+d,0,h,{locale:"en"})}});3<c&&(a["beginningOf"+e]=function(f,g){return qb(f,c,g)},a["endOf"+e]=function(f,g){return Pb(f,c,g)});a["add"+e+"s"]=function(f,g,h){return Ra(f,d,g,h)};a[d+"sAgo"]=a[d+"sUntil"]=function(f,g,h){return Qb(rb(f,g,h,!0).date,f,b)};a[d+"sSince"]=a[d+"sFromNow"]=function(f,g,h){return Qb(f,rb(f,g,h,!0).date,b)}})})();(function(){Ua(Aa,wa,function(a,b){var c=b.name;var d=function(g){return nb(g*b.f)};var e=function(g,h,k){return Ra(ya(h,k,!0),
c,g)};var f=function(g,h,k){return Ra(ya(h,k,!0),c,-g)};a[c]=d;a[c+"s"]=d;a[c+"Before"]=f;a[c+"sBefore"]=f;a[c+"Ago"]=f;a[c+"sAgo"]=f;a[c+"After"]=e;a[c+"sAfter"]=e;a[c+"FromNow"]=e;a[c+"sFromNow"]=e})})();(function(){var a=ra("Today Yesterday Tomorrow Weekday Weekend Future Past"),b=Sa.weekdays.slice(0,7),c=Sa.months.slice(0,12);Ua(W,a.concat(b).concat(c),function(d,e){d["is"+e]=function(f){return xd(f,e)}})})();Zc(W,ya);var kf=/[^\u0000-\u0040\u005B-\u0060\u007B-\u007F]+('s)?/g,jf=/(^|_)([^_]+)/g,
pf=/&#?(x)?([\w\d]{0,5});/gi,Xf=/[&<>]/g,Fd={lt:"<",gt:">",amp:"&",nbsp:" ",quot:'"',apos:"'"},Jc,mf="and or nor a an the so but to of at by from into on onto off out in over with for".split(" "),qf="area base br col command embed hr img input keygen link meta param source track wbr".split(" "),Yf=RegExp("^[\t\n\x0B\f\r \u00a0\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u2028\u2029\u3000\ufeff]+"),Zf=RegExp("[\t\n\x0B\f\r \u00a0\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u2028\u2029\u3000\ufeff]+$"),
nf=RegExp("(?=[\t\n\x0B\f\r \u00a0\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u2028\u2029\u3000\ufeff])"),$f=String.prototype.includes,Kc,Lc,ag=hd(Hb);S(ma,{includes:sa(function(a,b,c){if(!Da(b))return $f.call(a,b,c);c&&(a=a.slice(c));return b.test(a)})},["enhance","enhanceString"]);S(ma,{at:function(a,b,c){return dd(a,b,c,!0)},escapeURL:function(a,b){return b?encodeURIComponent(a):encodeURI(a)},unescapeURL:function(a,b){return b?decodeURI(a):decodeURIComponent(a)},
escapeHTML:function(a){return a.replace(Xf,function(b){return A(Jc,b)})},unescapeHTML:function(a){return of(a)},stripTags:function(a,b,c){return Hd(a,b,c,!0)},removeTags:function(a,b,c){return Hd(a,b,c,!1)},encodeBase64:function(a){return Kc(a)},decodeBase64:function(a){return Lc(a)},forEach:function(a,b,c){return tb(a,b,c)},chars:function(a,b,c){return tb(a,b,c)},words:function(a,b){return tb(a.trim(),/\S+/g,b)},lines:function(a,b){return tb(a.trim(),/^.*$/gm,b)},codes:function(a,b){return Ed(a,
b)},shift:function(a,b){var c="";b=b||0;Ed(a,function(d){c+=V(d+b)});return c},isBlank:function(a){return 0===a.trim().length},isEmpty:function(a){return 0===a.length},insert:function(a,b,c){c=E(c)?a.length:c;return a.slice(0,c)+b+a.slice(c)},remove:function(a,b){return a.replace(b,"")},removeAll:function(a,b){return Gd(a,b)},reverse:function(a){return a.split("").reverse().join("")},compact:function(a){return a.trim().replace(/([\r\n\s\u3000])+/g,function(b,c){return"\u3000"===c?c:" "})},from:function(a,
b){return a.slice(Jd(a,b,!0))},to:function(a,b){E(b)&&(b=a.length);return a.slice(0,Jd(a,b))},dasherize:function(a){return ub(a).replace(/_/g,"-")},underscore:function(a){return ub(a)},camelize:function(a,b){return hf(a,b)},spacify:function(a){return ub(a).replace(/_/g," ")},titleize:function(a){return lf(a)},parameterize:function(a,b){var c=b;void 0===c&&(c="-");var d=a.replace(/[^a-z0-9\-_]+/gi,c);c&&(c=RegExp(["^","+|","+$|(",")","+"].join($a(c)),"g"),d=d.replace(c,"$1"));return encodeURI(d.toLowerCase())},
truncate:function(a,b,c,d){return Dd(a,b,c,d)},truncateOnWord:function(a,b,c,d){return Dd(a,b,c,d,!0)},pad:function(a,b,c){b=Va(b);var d=aa(0,b-a.length)/2;b=bb(d);d=xa(d);return Tb(b,c)+a+Tb(d,c)},padLeft:function(a,b,c){b=Va(b);return Tb(aa(0,b-a.length),c)+a},padRight:function(a,b,c){b=Va(b);return a+Tb(aa(0,b-a.length),c)},first:function(a,b){E(b)&&(b=1);return a.substr(0,b)},last:function(a,b){E(b)&&(b=1);return a.substr(0>a.length-b?0:a.length-b)},toNumber:function(a,b){return kc(a,b)},capitalize:function(a,
b,c){return rc(a,b,c)},trimLeft:function(a){return a.replace(Yf,"")},trimRight:function(a){return a.replace(Zf,"")}});yb(ma,{replaceAll:function(a,b,c){return Gd(a,b,c)},format:function(a,b){var c=b[0]&&b[0].valueOf();1===b.length&&T(c)&&(b=c);return ag(a,b)}});(function(){function a(e){return function(f){try{return e(f)}catch(g){return""}}}if("undefined"!==typeof Buffer)Kc=function(e){return(new Buffer(e)).toString("base64")},Lc=function(e){return(new Buffer(e,"base64")).toString("utf8")};else{if("undefined"!==
typeof btoa){var b=a(btoa);var c=a(atob)}else{var d=/[^A-Za-z0-9\+\/=]/g;b=function(e){var f="",g=0;do{var h=e.charCodeAt(g++);var k=e.charCodeAt(g++);var l=e.charCodeAt(g++);var m=h>>2;h=(h&3)<<4|k>>4;var n=(k&15)<<2|l>>6;var p=l&63;isNaN(k)?n=p=64:isNaN(l)&&(p=64);f+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(m);f+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(h);f+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(n);
f+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(p)}while(g<e.length);return f};c=function(e){var f="",g=0;if(e.match(d))return"";e=e.replace(/[^A-Za-z0-9\+\/=]/g,"");do{var h="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(e.charAt(g++));var k="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(e.charAt(g++));var l="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(e.charAt(g++));var m="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(e.charAt(g++));
h=h<<2|k>>4;k=(k&15)<<4|l>>2;var n=(l&3)<<6|m;f+=V(h);64!=l&&(f+=V(k));64!=m&&(f+=V(n))}while(g<e.length);return f}}Kc=function(e){return b(unescape(encodeURIComponent(e)))};Lc=function(e){return decodeURIComponent(escape(c(e)))}}})();(function(){Jc={};B(Fd,function(a,b){Jc[a]="&"+b+";"})})();var bg=!("0"in[].concat(void 0).concat()),cg={sortIgnore:null,sortNatural:!0,sortIgnoreCase:!0,sortOrder:function(){return Fa("A\u00c1\u00c0\u00c2\u00c3\u0104BC\u0106\u010c\u00c7D\u010e\u00d0E\u00c9\u00c8\u011a\u00ca\u00cb\u0118FG\u011eH\u0131I\u00cd\u00cc\u0130\u00ce\u00cfJKL\u0141MN\u0143\u0147\u00d1O\u00d3\u00d2\u00d4PQR\u0158S\u015a\u0160\u015eT\u0164U\u00da\u00d9\u016e\u00db\u00dcVWXY\u00ddZ\u0179\u017b\u017d\u00de\u00c6\u0152\u00d8\u00d5\u00c5\u00c4\u00d6".split(""),
function(a){return a+a.toLowerCase()}).join("")}(),sortCollate:function(a,b){var c=0,d=0,e=eb("sortOrder");var f=eb("sortIgnore");var g=eb("sortNatural");var h=eb("sortIgnoreCase");var k=eb("sortEquivalents");a=Qd(a,f,h);b=Qd(b,f,h);do{var l=Rd(a,c,k);var m=Rd(b,c,k);f=l?e.indexOf(l):null;h=m?e.indexOf(m):null;-1===f||-1===h?(f=a.charCodeAt(c)||null,h=b.charCodeAt(c)||null,g&&(48<=f&&57>=f||65296<=f&&65305>=f)&&(48<=h&&57>=h||65296<=h&&65305>=h)&&(f=kc(a.slice(c)),h=kc(b.slice(c)))):(l=l!==a.charAt(c),
m=m!==b.charAt(c),l!==m&&0===d&&(d=l-m));c+=1}while(null!=f&&null!=h&&f===h);return f===h?d:f-h},sortEquivalents:function(){var a={};D(ra("A\u00c1\u00c0\u00c2\u00c3\u00c4 C\u00c7 E\u00c9\u00c8\u00ca\u00cb I\u00cd\u00cc\u0130\u00ce\u00cf O\u00d3\u00d2\u00d4\u00d5\u00d6 S\u00df U\u00da\u00d9\u00db\u00dc"),function(b){var c=b.charAt(0);D(b.slice(1).split(""),function(d){a[d]=c;a[d.toLowerCase()]=c.toLowerCase()})});return a}()},eb=ec(la,cg);Ma(la,{create:function(a,b){return Kd(a,b)},construct:function(a,
b){a=Va(a);return Array.from(Array(a),function(c,d){return b&&b(d)})}});S(la,{isEmpty:function(a){return 0===a.length},isEqual:function(a,b){return Oa(a,b)},clone:function(a){return db(a)},at:function(a,b,c){return dd(a,b,c)},add:function(a,b,c){return Ld(db(a),b,c)},subtract:function(a,b){return Od(a,b,!0)},append:function(a,b,c){return Ld(a,b,c)},removeAt:function(a,b,c){if(E(b))return a;E(c)&&(c=b);a.splice(b,c-b+1);return a},unique:function(a,b){return Md(a,b)},flatten:function(a,b){return Nd(a,
b)},first:function(a,b){if(E(b))return a[0];0>b&&(b=0);return a.slice(0,b)},last:function(a,b){return E(b)?a[a.length-1]:a.slice(0>a.length-b?0:a.length-b)},from:function(a,b){return a.slice(b)},to:function(a,b){E(b)&&(b=a.length);return a.slice(0,b)},compact:function(a,b){return tf(a,b)},groupBy:function(a,b,c){return uf(a,b,c)},inGroups:function(a,b,c){var d=y(c),e=Array(b),f=xa(a.length/b);Ib(b,function(g){var h=g*f,k=a.slice(h,h+f);d&&k.length<f&&Ib(f-k.length,function(){k.push(c)});e[g]=k});
return e},inGroupsOf:function(a,b,c){var d=[],e=a.length,f;if(0===e||0===b)return a;E(b)&&(b=1);E(c)&&(c=null);Ib(xa(e/b),function(g){for(f=a.slice(b*g,b*g+b);f.length<b;)f.push(c);d.push(f)});return d},shuffle:function(a){a=db(a);for(var b=a.length,c,d;b;)c=Math.random()*b|0,d=a[--b],a[b]=a[c],a[c]=d;return a},sample:function(a,b,c){var d=[];if(!fb(b)){var e=b;b=c}if(E(e)){e=1;var f=!0}b||(a=db(a));e=La(e,a.length);for(b=0;b<e;b++)c=da(Math.random()*a.length),d.push(a[c]),a.splice(c,1);return f?
d[0]:d},sortBy:function(a,b,c){a.sort(function(d,e){var f=Ea(d,b,a,[d]),g=Ea(e,b,a,[e]);return Pd(f,g)*(c?-1:1)});return a},remove:function(a,b){for(var c=ta(b),d=0;d<a.length;)c(a[d],d,a)?a.splice(d,1):d++;return a},exclude:function(a,b){for(var c=[],d=ta(b),e=0;e<a.length;e++)d(a[e],e,a)||c.push(a[e]);return c},union:function(a,b){var c=bg?sf(a,b):a.concat(b);return Md(c)},intersect:function(a,b){return Od(a,b,!1)}});yb(la,{zip:function(a,b){return Fa(a,function(c,d){return[c].concat(Fa(b,function(e){return d in
e?e[d]:null}))})}});qe(la,"insert","append");Zc(la,Kd);var xf=/^(.+?)(\[.*\])$/,Af=/[^\d.-]/,wc=Object.getOwnPropertyNames,Ud=Object.getOwnPropertySymbols,Vd=Object.getOwnPropertyDescriptor;cc=Object.prototype.toString;Ma(jb,{fromQueryString:function(a,b){return wf(a,b)}});dc(jb,{has:function(a,b,c){return Wa(a,b,c,!0)},get:function(a,b,c){return Hb(a,b,c)},set:function(a,b,c){Wa(a,b,!1,!1,!0,!1,c);return a},size:function(a){return Object.keys(lb(a)).length},isEmpty:function(a){return 0===Object.keys(lb(a)).length},
toQueryString:function(a,b){var c=b||{};E(c.separator)&&(c.separator="_");return sc(a,c.deep,c.transform,c.prefix||"",c.separator)},isEqual:function(a,b){return Oa(a,b)},merge:function(a,b,c){return uc(a,b,c)},add:function(a,b,c){return uc(xc(a),b,c)},mergeAll:function(a,b,c){return vc(a,b,c)},addAll:function(a,b,c){return vc(xc(a),b,c)},defaults:function(a,b,c){c=c||{};c.resolve=c.resolve||!1;return vc(a,b,c)},intersect:function(a,b){return Yd(a,b,!1)},subtract:function(a,b){return Yd(a,b,!0)},clone:function(a,
b){return xc(a,b)},values:function(a){return Cf(a)},invert:function(a,b){var c={};b=!0===b;B(a,function(d,e){J(c,d)&&b?c[d].push(e):c[d]=b?[e]:e});return c},tap:function(a,b){return Df(a,b)},isArguments:function(a){var b=ia(a);return!Ca(a)&&"length"in a&&("[object Arguments]"===b||!!a.callee)},isObject:function(a){return Gb(a)},remove:function(a,b){return Ef(a,b)},exclude:function(a,b){return Ff(a,b)},select:function(a,b){return Xd(a,b,!0)},reject:function(a,b){return Xd(a,b,!1)}});S(jb,{keys:function(a){return Object.keys(a)}});
(function(){var a=[fb,Q,H,ha,Da,X,P,Mb,Kb,Lb];Ie(jb,"Boolean Number String Date RegExp Function Array Error Set Map",function(b,c,d){b["is"+c]=a[d]})})();var dg=gb("map",ce),eg=gb("find",Ka),ue=gb("some",Ka),fg=gb("every",Ka),ve=gb("filter",Ka),gg=gb("findIndex",Ka);S(la,{map:sa(dg),some:sa(ue),every:sa(fg),filter:sa(ve),find:sa(eg),findIndex:sa(gg)},["enhance","enhanceArray"]);S(la,{none:sa(function(){return!ue.apply(this,arguments)}),count:sa(function(a,b){return E(b)?a.length:ve.apply(this,arguments).length}),
min:function(a,b,c){return wb(a,b,c)},max:function(a,b,c){return wb(a,b,c,!0)},least:function(a,b,c){return Vb(a,b,c)},most:function(a,b,c){return Vb(a,b,c,!0)},sum:function(a,b){return Zd(a,b)},average:function(a,b){return $d(a,b)},median:function(a,b){return ae(a,b)}});var we=yc("some"),hg=yc("find"),ig=yc("every");dc(jb,{forEach:function(a,b){return Gf(a,b)},map:function(a,b){return Hf(a,b)},some:we,every:ig,filter:function(a,b){return Jf(a,b)},reduce:function(a,b,c){return If(a,b,c)},find:hg,
count:function(a,b){return Kf(a,b)},none:function(a,b){return!we(a,b)},sum:function(a,b){return Zd(a,b)},average:function(a,b){return $d(a,b)},median:function(a,b){return ae(a,b)},min:function(a,b,c){return wb(a,b,c,!1,!0)},max:function(a,b,c){return wb(a,b,c,!0,!0)},least:function(a,b,c){return Vb(a,b,c,!1,!0)},most:function(a,b,c){return Vb(a,b,c,!0,!0)}});(function(){function a(f,g,h){var k=f;g&&(k=f.slice(g),h&&(k=k.concat(f.slice(0,g))));return k}function b(f,g){return La(g,aa(0,f))}function c(f,
g,h,k,l,m){return function(n,p,q){q=hc(q+g,l,m);return h.call(f,n,p,q,f)}}function d(f,g,h,k,l,m){return function(n,p){p=hc(p+g,l,m);return h.call(k,f[p],p,f)}}function e(f,g){var h=g.i||Array.prototype[f],k=g.apply||d,l=g.slice||a,m=g.clamp||b,n=g.result,p=g.v;return function(q,t,w){var v=[],u=0,r;var x=q.length;fb(w[0])&&(r=w[u++]);var z=w[u++];u=w[u];0>t&&(t+=x);t=m(t,x);Yc(w.length);z=p?p(z,u):z;v.push(k(q,t,z,u,x,r));u&&v.push(u);q=h.apply(l(q,t,r),v);n&&(q=n(q,t,x));return q}}B({forEach:{i:function(f){D(this,
f)}},map:{v:ce},"some every":{v:Ka},findIndex:{v:Ka,result:function(f,g,h){-1!==f&&(f=(f+g)%h);return f}},reduce:{apply:c},"filter find":{v:Ka},reduceRight:{apply:c,slice:function(f,g,h){h||(f=f.slice(0,aa(0,g+1)));return f},clamp:function(f,g){return La(g,aa(-1,f))}}},function(f,g){D(ra(g),function(h){var k=h+"FromIndex";h=e(h,f);yb(la,k,h)})})})();var ee=ec(Aa,{decimal:".",thousands:","});Ma(Aa,{random:function(a,b){1==arguments.length&&(b=a,a=0);var c=La(a||0,E(b)?1:b);var d=aa(a||0,E(b)?1:b)+
1;return da(Math.random()*(d-c)+c)}});S(Aa,{isInteger:function(a){return 0===a%1},isOdd:function(a){return 0===a%1&&0!==a%2},isEven:function(a){return 0===a%2},isMultipleOf:function(a,b){return 0===a%b},log:function(a,b){return Math.log(a)/(b?Math.log(b):1)},abbr:function(a,b){return zc(a,b,"|kmbt")},metric:function(a,b,c){"all"===c?c="yzafpn\u03bcm|KMGTPEZY":c||(c="n\u03bcm|k");return zc(a,b,c)},bytes:function(a,b,c,d){"binary"===d||!d&&c?d="|,Ki,Mi,Gi,Ti,Pi,Ei":"si"!==d&&d||(d="|KMGTPE");return zc(a,
b,d,c)+"B"},format:function(a,b){return de(a,b)},hex:function(a,b){return ea(a,b||1,!1,16)},times:function(a,b){for(var c,d,e=0;e<a;e++)d=b.call(a,e),y(d)&&(c||(c=[]),c.push(d));return c},chr:function(a){return V(a)},pad:function(a,b,c,d){return ea(a,b,c,d)},ordinalize:function(a){var b=+oa(a).toString().slice(-2);return a+fd(b)},toNumber:function(a){return a.valueOf()},round:Ac(nb),ceil:Ac(xa),floor:Ac(bb)});(function(){Ua(Aa,"abs pow sin asin cos acos tan atan exp pow sqrt",function(a,b){a[b]=function(c,
d){return Math[b](c.valueOf(),d)}})})();var ac=kb("lock"),Wb=kb("timers"),xe=kb("partial"),Bc=kb("canceled"),jg=Object.create||function(a){function b(){}b.prototype=a;return new b};S(Gc,{lazy:function(a,b,c,d){return ge(a,b,c,d)},throttle:function(a,b){return ge(a,b,!0,1)},debounce:function(a,b){function c(){for(var d=[],e=0,f=arguments.length;e<f;e++)d.push(arguments[e]);fe(c);hb(c,b,a,this,d)}return c},cancel:function(a){return fe(a)},after:function(a,b){var c=0,d=[];b=Va(b);return function(){for(var e=
[],f=0,g=arguments.length;f<g;f++)e.push(arguments[f]);d.push(e);c++;if(c>=b)return a.call(this,d)}},once:function(a){var b=!1,c;return function(){if(b)return c;b=!0;return c=a.apply(this,arguments)}},memoize:function(a,b,c){if(!Q(b)){var d=b;b=c}if(H(d)){var e=d;d=function(f){return Hb(f,e)}}else d||(d=Lf);return Mf(a,d,b)},lock:function(a,b){if(xe(a))return ac(a,Q(b)?b:null),a;var c=function(){arguments.length=La(ac(c),arguments.length);return a.apply(this,arguments)};ac(c,Q(b)?b:a.length);return c}});
yb(Gc,{partial:function(a,b){function c(){var e=0,f=[],g=this,h=ac(c),k;for(k=0;k<d;k++){var l=b[k];y(l)?f[k]=l:f[k]=arguments[e++]}for(k=e;k<arguments.length;k++)f.push(arguments[k]);null===h&&(h=d);Q(h)&&(f.length=La(f.length,h));return g instanceof c?(g=jg(a.prototype),e=a.apply(g,f),T(e)?e:g):a.apply(g,f)}var d=b.length;xe(c,!0);return c},delay:function(a,b,c){hb(a,b,a,a,c);return a},every:function(a,b,c){function d(){hb(a,b,d);a.apply(a,c)}hb(a,b,d);return a}});Ma(pe,{escape:function(a){return $a(a)}});
S(pe,{getFlags:function(a){return Za(a)},setFlags:function(a,b){return RegExp(a.source,b)},addFlags:function(a,b){return RegExp(a.source,Za(a,b))},removeFlags:function(a,b){var c=RegExp("["+b+"]","g");return RegExp(a.source,Za(a).replace(c,""))}});var Of=/(\d+)?\s*(year|month|week|day|hour|minute|second|millisecond)s?/i,ne={Hours:36E5,Minutes:6E4,Seconds:1E3,Milliseconds:1};Xc(ca,{toString:function(){return Xb(this)?this.start+".."+this.end:"Invalid Range"},isValid:function(){return Xb(this)},span:function(){var a=
he(this.end)-he(this.start);return Xb(this)?oa(a)+1:NaN},contains:function(a){return null==a?!1:a.start&&a.end?a.start>=this.start&&a.start<=this.end&&a.end>=this.start&&a.end<=this.end:a>=this.start&&a<=this.end},every:function(a,b){return Yb(this,a,!1,b)},toArray:function(){return Yb(this)},union:function(a){return new ca(this.start<a.start?this.start:a.start,this.end>a.end?this.end:a.end)},intersect:function(a){return a.start>this.end||a.end<this.start?new ca(NaN,NaN):new ca(this.start>a.start?
this.start:a.start,this.end<a.end?this.end:a.end)},clone:function(){return new ca(this.start,this.end)},clamp:function(a){return Dc(this,a)}});Ma(Aa,{range:Nc});S(Aa,{upto:function(a,b,c,d){return Yb(new ca(a,b),c,!1,d)},clamp:function(a,b,c){return Dc(new ca(b,c),a)},cap:function(a,b){return Dc(new ca(void 0,b),a)}});qe(Aa,"downto","upto");Ma(ma,{range:Nc});var kg=/(?:from)?\s*(.+)\s+(?:to|until)\s+(.+)$/i,lg=/(.+)\s*for\s*((?:\d+)?\s*(?:year|month|week|day|hour|minute|second|millisecond))s?/i,mg=
/(?:for)?\s*((?:\d+)?\s*(?:year|month|week|day|hour|minute|second|millisecond))s?\s*(?:starting)?\s(?:at\s)?(.+)/i;Ma(W,{range:function(a,b){var c;if(1===arguments.length&&H(a))if(W.get&&(c=a.match(kg))){var d=ib(c[1].replace("from","at"));var e=W.get(d,c[2]);c=new ca(d,e)}else{if(c=a.match(mg)){var f=c[1];d=c[2]}if(c=a.match(lg))d=c[1],f=c[2];d&&f?(d=ib(d),c=le(f),e=me(d,c[0],c[1])):d=a;c=new ca(ib(d),ib(e))}else c=new ca(ib(a),ib(b));return c}});(function(){var a={};D("year month week day hour minute second millisecond".split(" "),
function(b,c){var d=b+"s";if(4>c)var e=function(){return Yb(this,b,!0)};else{var f=ne[Ya(d)];e=function(){return da((this.end-this.start)/f)}}a[d]=e});Xc(ca,a)})();var Ec,Mc;S(ma,{pluralize:function(a,b){a=String(a);return 1===b||0===a.length?a:Mc("plural",a)},singularize:function(a){return Mc("singular",String(a))},humanize:function(a){a=ng(a);a=a.replace(/(_)?([a-z\d]*)/gi,function(b,c,d){d=N.human&&N.human.find(d)||d;d=N.acronyms&&N.acronyms.find(d)||d.toLowerCase();return(c?" ":"")+d});return Ya(a)}});
Wc(ma,"addAcronym",function(a){xb("acronyms",a,a);xb("acronyms",a.toLowerCase(),a);Qf()});L(ma,"addPlural",I);L(ma,"addHuman",oe);(function(){Ec=function(){this.map={};this.rules=[]};Ec.prototype={add:function(a,b){H(a)?this.map[a]=b:this.rules.unshift({K:a,Y:b})},W:function(a){a=a.split(" ");var b=a.length-1;var c=a[b];a[b]=this.find(c)||this.L(c);return a.join(" ")},find:function(a){return A(this.map,a)},L:function(a){for(var b=0,c;c=this.rules[b];b++)if(c.K.test(a)){a=a.replace(c.K,c.Y);break}return a}}})();
(function(){Mc=function(a,b){return N[a]&&N[a].W(b)||b};I(/$/,"s");I(/s$/i,"s");I(/(ax|test)is$/i,"$1es");I(/(octop|fung|foc|radi|alumn|cact)(i|us)$/i,"$1i");I(/(census|alias|status|fetus|genius|virus)$/i,"$1es");I(/(bu)s$/i,"$1ses");I(/(buffal|tomat)o$/i,"$1oes");I(/([ti])um$/i,"$1a");I(/([ti])a$/i,"$1a");I(/sis$/i,"ses");I(/f+e?$/i,"ves");I(/(cuff|roof)$/i,"$1s");I(/([ht]ive)$/i,"$1s");I(/([^aeiouy]o)$/i,"$1es");I(/([^aeiouy]|qu)y$/i,"$1ies");I(/(x|ch|ss|sh)$/i,"$1es");I(/(tr|vert)(?:ix|ex)$/i,
"$1ices");I(/([ml])ouse$/i,"$1ice");I(/([ml])ice$/i,"$1ice");I(/^(ox)$/i,"$1en");I(/^(oxen)$/i,"$1");I(/(quiz)$/i,"$1zes");I(/(phot|cant|hom|zer|pian|portic|pr|quart|kimon)o$/i,"$1os");I(/(craft)$/i,"$1");I(/([ft])[eo]{2}(th?)$/i,"$1ee$2");G(/s$/i,"");G(/([pst][aiu]s)$/i,"$1");G(/([aeiouy])ss$/i,"$1ss");G(/(n)ews$/i,"$1ews");G(/([ti])a$/i,"$1um");G(/((a)naly|(b)a|(d)iagno|(p)arenthe|(p)rogno|(s)ynop|(t)he)ses$/i,"$1$2sis");G(/(^analy)ses$/i,"$1sis");G(/(i)(f|ves)$/i,"$1fe");G(/([aeolr]f?)(f|ves)$/i,
"$1f");G(/([ht]ive)s$/i,"$1");G(/([^aeiouy]|qu)ies$/i,"$1y");G(/(s)eries$/i,"$1eries");G(/(m)ovies$/i,"$1ovie");G(/(x|ch|ss|sh)es$/i,"$1");G(/([ml])(ous|ic)e$/i,"$1ouse");G(/(bus)(es)?$/i,"$1");G(/(o)es$/i,"$1");G(/(shoe)s?$/i,"$1");G(/(cris|ax|test)[ie]s$/i,"$1is");G(/(octop|fung|foc|radi|alumn|cact)(i|us)$/i,"$1us");G(/(census|alias|status|fetus|genius|virus)(es)?$/i,"$1");G(/^(ox)(en)?/i,"$1");G(/(vert)(ex|ices)$/i,"$1ex");G(/tr(ix|ices)$/i,"trix");G(/(quiz)(zes)?$/i,"$1");G(/(database)s?$/i,"$1");
G(/ee(th?)$/i,"oo$1");za("person","people");za("man","men");za("human","humans");za("child","children");za("sex","sexes");za("move","moves");za("save","saves");za("goose","geese");za("zombie","zombies");Pf("equipment information rice money species series fish deer sheep jeans")})();var ng=id;oe(/_id$/g,"");var ye=/[\u0020-\u00A5]|[\uFF61-\uFF9F][\uff9e\uff9f]?/g,og=/[\u2212\u3000-\u301C\u301A-\u30FC\uFF01-\uFF60\uFFE0-\uFFE6]/g,pg=/[\u30ab\u30ad\u30af\u30b1\u30b3\u30b5\u30b7\u30b9\u30bb\u30bd\u30bf\u30c1\u30c4\u30c6\u30c8\u30cf\u30d2\u30d5\u30d8\u30db]/,
qg=/[\u30cf\u30d2\u30d5\u30d8\u30db\u30f2]/,rg=[{name:"Arabic",src:"\u0600-\u06ff"},{name:"Cyrillic",src:"\u0400-\u04ff"},{name:"Devanagari",src:"\u0900-\u097f"},{name:"Greek",src:"\u0370-\u03ff"},{name:"Hangul",src:"\uac00-\ud7af\u1100-\u11ff"},{name:"Han Kanji",src:"\u4e00-\u9fff\uf900-\ufaff"},{name:"Hebrew",src:"\u0590-\u05ff"},{name:"Hiragana",src:"\u3040-\u309f\u30fb-\u30fc"},{name:"Kana",src:"\u3040-\u30ff\uff61-\uff9f"},{name:"Katakana",src:"\u30a0-\u30ff\uff61-\uff9f"},{name:"Latin",src:"\u0001-\u007f\u0080-\u00ff\u0100-\u017f\u0180-\u024f"},
{name:"Thai",src:"\u0e00-\u0e7f"}],sg=[{type:"a",start:65,end:90},{type:"a",start:97,end:122},{type:"n",start:48,end:57},{type:"p",start:33,end:47},{type:"p",start:58,end:64},{type:"p",start:91,end:96},{type:"p",start:123,end:126}],Zb;S(ma,{hankaku:function(a,b){return Fc(a,b,og,"hankaku")},zenkaku:function(a,b){return Fc(a,b,ye,"zenkaku")},hiragana:function(a,b){!1!==b&&(a=Fc(a,"k",ye,"zenkaku"));return a.replace(/[\u30A1-\u30F6]/g,function(c){return V(c.charCodeAt(0)+-96)})},katakana:function(a){return a.replace(/[\u3041-\u3096]/g,
function(b){return V(b.charCodeAt(0)+96)})}});(function(){Ua(ma,rg,function(a,b){var c=RegExp("^["+b.src+"\\s]+$"),d=RegExp("["+b.src+"]");D(ra(b.name),function(e){a["is"+e]=function(f){return c.test(f.trim())};a["has"+e]=function(f){return d.test(f.trim())}})})})();(function(){function a(d,e,f){b("zenkaku",d,e,f);b("hankaku",d,f,e)}function b(d,e,f,g,h){var k=Zb[d][f]||{};!1!==h&&(k.all=g);k[e]=g;Zb[d][f]=k}var c;Zb={zenkaku:{},hankaku:{}};D(sg,function(d){Ib(d.end-d.start+1,function(e){e+=d.start;
a(d.type,V(e),V(e+65248))})});(function(){for(var d=0;57>d;d++){var e="\u30a2\u30a4\u30a6\u30a8\u30aa\u30a1\u30a3\u30a5\u30a7\u30a9\u30ab\u30ad\u30af\u30b1\u30b3\u30b5\u30b7\u30b9\u30bb\u30bd\u30bf\u30c1\u30c4\u30c3\u30c6\u30c8\u30ca\u30cb\u30cc\u30cd\u30ce\u30cf\u30d2\u30d5\u30d8\u30db\u30de\u30df\u30e0\u30e1\u30e2\u30e4\u30e3\u30e6\u30e5\u30e8\u30e7\u30e9\u30ea\u30eb\u30ec\u30ed\u30ef\u30f2\u30f3\u30fc\u30fb".charAt(d);c="\uff71\uff72\uff73\uff74\uff75\uff67\uff68\uff69\uff6a\uff6b\uff76\uff77\uff78\uff79\uff7a\uff7b\uff7c\uff7d\uff7e\uff7f\uff80\uff81\uff82\uff6f\uff83\uff84\uff85\uff86\uff87\uff88\uff89\uff8a\uff8b\uff8c\uff8d\uff8e\uff8f\uff90\uff91\uff92\uff93\uff94\uff6c\uff95\uff6d\uff96\uff6e\uff97\uff98\uff99\uff9a\uff9b\uff9c\uff66\uff9d\uff70\uff65".charAt(d);
a("k",c,e);e.match(pg)&&a("k",c+"\uff9e",V(e.charCodeAt(0)+1));e.match(qg)&&a("k",c+"\uff9f",V(e.charCodeAt(0)+2))}})();(function(){for(var d=0;7>d;d++)a("p","\uff61\uff64\uff62\uff63\u00a5\u00a2\u00a3".charAt(d),"\u3002\u3001\u300c\u300d\uffe5\uffe0\uffe1".charAt(d))})();a("s"," ","\u3000");a("k","\uff73\uff9e","\u30f4");a("k","\uff66\uff9e","\u30fa");b("hankaku","n","\u2212","-");b("hankaku","n","\u30fc","-",!1);b("zenkaku","n","-","\uff0d",!1)})()}).call(this);